window.MCPD_LATE_RESPONSES = [
    "Well he got there before me that doesn't mean I get doesn't mean I get to get paid but I'll move it anyways and kill the bastard",
    "Aw man, he beat me there, guess I'll just drive around.",
    "Aw man, he beat me there, no action for me.",
    "Aw man, he beat me there, back to eating my donut.",
    "Aw man, he beat me there, my sirens were on for nothing.",
    "Aw man, he beat me there, time to go back to sleep.",
    "Aw man, he beat me there, I'll just cancel my route.",
    "Aw man, he beat me there, whatever.",
    "Aw man, he beat me there, I'm so bored.",
    "Aw man, I'm too late, guess I'll just drive around.",
    "Aw man, I'm too late, no action for me.",
    "Aw man, I'm too late, back to eating my donut.",
    "Aw man, I'm too late, my sirens were on for nothing.",
    "Aw man, I'm too late, time to go back to sleep.",
    "Aw man, I'm too late, I'll just cancel my route.",
    "Aw man, I'm too late, whatever.",
    "Aw man, I'm too late, I'm so bored.",
    "Aw man, they took my call, guess I'll just drive around.",
    "Aw man, they took my call, no action for me.",
    "Aw man, they took my call, back to eating my donut.",
    "Aw man, they took my call, my sirens were on for nothing.",
    "Aw man, they took my call, time to go back to sleep.",
    "Aw man, they took my call, I'll just cancel my route.",
    "Aw man, they took my call, whatever.",
    "Aw man, they took my call, I'm so bored.",
    "Aw man, I was so close, guess I'll just drive around.",
    "Aw man, I was so close, no action for me.",
    "Aw man, I was so close, back to eating my donut.",
    "Aw man, I was so close, my sirens were on for nothing.",
    "Aw man, I was so close, time to go back to sleep.",
    "Aw man, I was so close, I'll just cancel my route.",
    "Aw man, I was so close, whatever.",
    "Aw man, I was so close, I'm so bored.",
    "Aw man, I was literally a block away, guess I'll just drive around.",
    "Aw man, I was literally a block away, no action for me.",
    "Aw man, I was literally a block away, back to eating my donut.",
    "Aw man, I was literally a block away, my sirens were on for nothing.",
    "Aw man, I was literally a block away, time to go back to sleep.",
    "Aw man, I was literally a block away, I'll just cancel my route.",
    "Aw man, I was literally a block away, whatever.",
    "Aw man, I was literally a block away, I'm so bored.",
    "Aw man, my cruiser is too slow, guess I'll just drive around.",
    "Aw man, my cruiser is too slow, no action for me.",
    "Aw man, my cruiser is too slow, back to eating my donut.",
    "Aw man, my cruiser is too slow, my sirens were on for nothing.",
    "Aw man, my cruiser is too slow, time to go back to sleep.",
    "Aw man, my cruiser is too slow, I'll just cancel my route.",
    "Aw man, my cruiser is too slow, whatever.",
    "Aw man, my cruiser is too slow, I'm so bored.",
    "Aw man, I missed all the fun, guess I'll just drive around.",
    "Aw man, I missed all the fun, no action for me.",
    "Aw man, I missed all the fun, back to eating my donut.",
    "Aw man, I missed all the fun, my sirens were on for nothing.",
    "Aw man, I missed all the fun, time to go back to sleep.",
    "Aw man, I missed all the fun, I'll just cancel my route.",
    "Aw man, I missed all the fun, whatever.",
    "Aw man, I missed all the fun, I'm so bored.",
    "Aw man, they stole my glory, guess I'll just drive around.",
    "Aw man, they stole my glory, no action for me.",
    "Aw man, they stole my glory, back to eating my donut.",
    "Aw man, they stole my glory, my sirens were on for nothing.",
    "Aw man, they stole my glory, time to go back to sleep.",
    "Aw man, they stole my glory, I'll just cancel my route.",
    "Aw man, they stole my glory, whatever.",
    "Aw man, they stole my glory, I'm so bored.",
    "Darn it, he beat me there, guess I'll just drive around.",
    "Darn it, he beat me there, no action for me.",
    "Darn it, he beat me there, back to eating my donut.",
    "Darn it, he beat me there, my sirens were on for nothing.",
    "Darn it, he beat me there, time to go back to sleep.",
    "Darn it, he beat me there, I'll just cancel my route.",
    "Darn it, he beat me there, whatever.",
    "Darn it, he beat me there, I'm so bored.",
    "Darn it, I'm too late, guess I'll just drive around.",
    "Darn it, I'm too late, no action for me.",
    "Darn it, I'm too late, back to eating my donut.",
    "Darn it, I'm too late, my sirens were on for nothing.",
    "Darn it, I'm too late, time to go back to sleep.",
    "Darn it, I'm too late, I'll just cancel my route.",
    "Darn it, I'm too late, whatever.",
    "Bruh, he must have been flying, I'm going to pull them over later.",
    "Bruh, he must have been flying, I'm telling the chief.",
    "Bruh, he must have been flying, whatever, I'm getting coffee.",
    "Bruh, he must have been flying, I'm not even mad.",
    "Bruh, he must have been flying, I'll just watch from here.",
    "Bruh, he must have been flying, let me know if you need a bodybag.",
    "Bruh, he must have been flying, try not to shoot yourselves.",
    "Bruh, he must have been flying, leave some for me.",
    "Bruh, did they use a teleporter?, I'm going to pull them over later.",
    "Bruh, did they use a teleporter?, I'm telling the chief.",
    "Bruh, did they use a teleporter?, whatever, I'm getting coffee.",
    "Bruh, did they use a teleporter?, I'm not even mad.",
    "Bruh, did they use a teleporter?, I'll just watch from here.",
    "Bruh, did they use a teleporter?, let me know if you need a bodybag.",
    "Bruh, did they use a teleporter?, try not to shoot yourselves.",
    "Bruh, did they use a teleporter?, leave some for me.",
    "Bruh, they stole my arrest, I'm going to pull them over later.",
    "Bruh, they stole my arrest, I'm telling the chief.",
    "Bruh, they stole my arrest, whatever, I'm getting coffee.",
    "Bruh, they stole my arrest, I'm not even mad.",
    "Bruh, they stole my arrest, I'll just watch from here.",
    "Bruh, they stole my arrest, let me know if you need a bodybag.",
    "Bruh, they stole my arrest, try not to shoot yourselves.",
    "Bruh, they stole my arrest, leave some for me.",
    "Bruh, I bet they just wanted the overtime, I'm going to pull them over later.",
    "Bruh, I bet they just wanted the overtime, I'm telling the chief.",
    "Bruh, I bet they just wanted the overtime, whatever, I'm getting coffee.",
    "Bruh, I bet they just wanted the overtime, I'm not even mad.",
    "Bruh, I bet they just wanted the overtime, I'll just watch from here.",
    "Bruh, I bet they just wanted the overtime, let me know if you need a bodybag.",
    "Bruh, I bet they just wanted the overtime, try not to shoot yourselves.",
    "Bruh, I bet they just wanted the overtime, leave some for me.",
    "Bruh, they're going to steal all the evidence, I'm going to pull them over later.",
    "Bruh, they're going to steal all the evidence, I'm telling the chief.",
    "Bruh, they're going to steal all the evidence, whatever, I'm getting coffee.",
    "Bruh, they're going to steal all the evidence, I'm not even mad.",
    "Bruh, they're going to steal all the evidence, I'll just watch from here.",
    "Bruh, they're going to steal all the evidence, let me know if you need a bodybag.",
    "Bruh, they're going to steal all the evidence, try not to shoot yourselves.",
    "Bruh, they're going to steal all the evidence, leave some for me.",
    "Bruh, I was going to tase that guy, I'm going to pull them over later.",
    "Bruh, I was going to tase that guy, I'm telling the chief.",
    "Bruh, I was going to tase that guy, whatever, I'm getting coffee.",
    "Bruh, I was going to tase that guy, I'm not even mad.",
    "Bruh, I was going to tase that guy, I'll just watch from here.",
    "Bruh, I was going to tase that guy, let me know if you need a bodybag.",
    "Bruh, I was going to tase that guy, try not to shoot yourselves.",
    "Bruh, I was going to tase that guy, leave some for me.",
    "Bruh, they're going to take all the credit, I'm going to pull them over later.",
    "Bruh, they're going to take all the credit, I'm telling the chief.",
    "Bruh, they're going to take all the credit, whatever, I'm getting coffee.",
    "Bruh, they're going to take all the credit, I'm not even mad.",
    "Bruh, they're going to take all the credit, I'll just watch from here.",
    "Bruh, they're going to take all the credit, let me know if you need a bodybag.",
    "Bruh, they're going to take all the credit, try not to shoot yourselves.",
    "Bruh, they're going to take all the credit, leave some for me.",
    "Bruh, I hope they trip, I'm going to pull them over later.",
    "Bruh, I hope they trip, I'm telling the chief.",
    "Bruh, I hope they trip, whatever, I'm getting coffee.",
    "Bruh, I hope they trip, I'm not even mad.",
    "Bruh, I hope they trip, I'll just watch from here.",
    "Bruh, I hope they trip, let me know if you need a bodybag.",
    "Bruh, I hope they trip, try not to shoot yourselves.",
    "Bruh, I hope they trip, leave some for me.",
    "Bruh, he's such a tryhard, I'm going to pull them over later.",
    "Bruh, he's such a tryhard, I'm telling the chief.",
    "Bruh, he's such a tryhard, whatever, I'm getting coffee.",
    "Bruh, he's such a tryhard, I'm not even mad.",
    "Bruh, he's such a tryhard, I'll just watch from here.",
    "Bruh, he's such a tryhard, let me know if you need a bodybag.",
    "Bruh, he's such a tryhard, try not to shoot yourselves.",
    "Bruh, he's such a tryhard, leave some for me.",
    "Lol, he must have been flying, I'm going to pull them over later.",
    "Lol, he must have been flying, I'm telling the chief.",
    "Lol, he must have been flying, whatever, I'm getting coffee.",
    "Lol, he must have been flying, I'm not even mad.",
    "Lol, he must have been flying, I'll just watch from here.",
    "Lol, he must have been flying, let me know if you need a bodybag.",
    "Lol, he must have been flying, try not to shoot yourselves.",
    "Lol, he must have been flying, leave some for me.",
    "Listen here, you stole my collar, I'm slashing your tires.",
    "Listen here, you stole my collar, back off next time.",
    "Listen here, you stole my collar, I hate this precinct.",
    "Listen here, you stole my collar, I'm writing you up.",
    "Listen here, you stole my collar, I'm going to tase you.",
    "Listen here, you stole my collar, stay out of my way.",
    "Listen here, you stole my collar, you owe me 500 credits.",
    "Listen here, you stole my collar, I'm turning off my radio.",
    "Listen here, you cut me off, I'm slashing your tires.",
    "Listen here, you cut me off, back off next time.",
    "Listen here, you cut me off, I hate this precinct.",
    "Listen here, you cut me off, I'm writing you up.",
    "Listen here, you cut me off, I'm going to tase you.",
    "Listen here, you cut me off, stay out of my way.",
    "Listen here, you cut me off, you owe me 500 credits.",
    "Listen here, you cut me off, I'm turning off my radio.",
    "Listen here, I had that sector locked down, I'm slashing your tires.",
    "Listen here, I had that sector locked down, back off next time.",
    "Listen here, I had that sector locked down, I hate this precinct.",
    "Listen here, I had that sector locked down, I'm writing you up.",
    "Listen here, I had that sector locked down, I'm going to tase you.",
    "Listen here, I had that sector locked down, stay out of my way.",
    "Listen here, I had that sector locked down, you owe me 500 credits.",
    "Listen here, I had that sector locked down, I'm turning off my radio.",
    "Listen here, you're always taking my calls, I'm slashing your tires.",
    "Listen here, you're always taking my calls, back off next time.",
    "Listen here, you're always taking my calls, I hate this precinct.",
    "Listen here, you're always taking my calls, I'm writing you up.",
    "Listen here, you're always taking my calls, I'm going to tase you.",
    "Listen here, you're always taking my calls, stay out of my way.",
    "Listen here, you're always taking my calls, you owe me 500 credits.",
    "Listen here, you're always taking my calls, I'm turning off my radio.",
    "Listen here, I was already en route, I'm slashing your tires.",
    "Listen here, I was already en route, back off next time.",
    "Listen here, I was already en route, I hate this precinct.",
    "Listen here, I was already en route, I'm writing you up.",
    "Listen here, I was already en route, I'm going to tase you.",
    "Listen here, I was already en route, stay out of my way.",
    "Listen here, I was already en route, you owe me 500 credits.",
    "Listen here, I was already en route, I'm turning off my radio.",
    "Listen here, you just want the bounty, I'm slashing your tires.",
    "Listen here, you just want the bounty, back off next time.",
    "Listen here, you just want the bounty, I hate this precinct.",
    "Listen here, you just want the bounty, I'm writing you up.",
    "Listen here, you just want the bounty, I'm going to tase you.",
    "Listen here, you just want the bounty, stay out of my way.",
    "Listen here, you just want the bounty, you owe me 500 credits.",
    "Listen here, you just want the bounty, I'm turning off my radio.",
    "Listen here, you don't even know what you're doing, I'm slashing your tires.",
    "Listen here, you don't even know what you're doing, back off next time.",
    "Listen here, you don't even know what you're doing, I hate this precinct.",
    "Listen here, you don't even know what you're doing, I'm writing you up.",
    "Listen here, you don't even know what you're doing, I'm going to tase you.",
    "Listen here, you don't even know what you're doing, stay out of my way.",
    "Listen here, you don't even know what you're doing, you owe me 500 credits.",
    "Listen here, you don't even know what you're doing, I'm turning off my radio.",
    "Listen here, you're a terrible officer, I'm slashing your tires.",
    "Listen here, you're a terrible officer, back off next time.",
    "Listen here, you're a terrible officer, I hate this precinct.",
    "Listen here, you're a terrible officer, I'm writing you up.",
    "Listen here, you're a terrible officer, I'm going to tase you.",
    "Listen here, you're a terrible officer, stay out of my way.",
    "Listen here, you're a terrible officer, you owe me 500 credits.",
    "Listen here, you're a terrible officer, I'm turning off my radio.",
    "You idiot, you stole my collar, I'm slashing your tires.",
    "You idiot, you stole my collar, back off next time.",
    "You idiot, you stole my collar, I hate this precinct.",
    "You idiot, you stole my collar, I'm writing you up.",
    "You idiot, you stole my collar, I'm going to tase you.",
    "You idiot, you stole my collar, stay out of my way.",
    "You idiot, you stole my collar, you owe me 500 credits.",
    "You idiot, you stole my collar, I'm turning off my radio.",
    "You idiot, you cut me off, I'm slashing your tires.",
    "You idiot, you cut me off, back off next time.",
    "You idiot, you cut me off, I hate this precinct.",
    "You idiot, you cut me off, I'm writing you up."
];