// ==========================================
// MASSIVE NPC PERSONALITY ENGINE v3
// ==========================================
// Handles highly realistic reactions based on word boundaries, tone, length, and content.

const fallbackReactions = [
    "10-4. Copy.",
    "Roger that, Dispatch.",
    "Loud and clear.",
    "Copy. Patrol continuing.",
    "Understood.",
    "Solid copy.",
    "10-4, showing en route.",
    "Acknowledged.",
    "Copy that. Keeping eyes open.",
    "Copy. We're on it.",
    "10-4, moving out.",
    "Roger. Out.",
    "Copy, Dispatch. Be advised traffic is heavy.",
    "Understood. Proceeding.",
    "Copy that, standing by.",
    "10-4. Will advise when on scene.",
    "Roger. Over.",
    "Copy, switching channels.",
    "10-4, taking the long way around Sector 4.",
    "Understood, Dispatch. Stay frosty.",
    "10-4. Do we have any riot gear left in the armory?",
    "Acknowledged. My hover-cruiser is making that weird noise again.",
    "Roger. I'm pretty sure someone just tried to hack my steering wheel.",
    "Solid copy. Wait, are we still under martial law?",
    "Solid copy. My partner is asleep, I'm handling this alone.",
    "Loud and clear. I'm not doing any more paperwork today, just saying.",
    "Solid copy. Does anyone else smell burning plastic?",
    "10-4. I dropped my gun in a puddle of bio-sludge.",
    "Understood. Just don't send me back to the Gamma Slums.",
    "Roger. I'm not doing any more paperwork today, just saying.",
    "Understood. Wait, are we still under martial law?",
    "10-4. I think my cruiser just became sentient. It's judging my driving.",
    "Copy that. My cruiser's AC is blowing out neon smoke.",
    "Copy that. I just hit a pothole the size of a crater.",
    "Roger. I think my comms are tapped by a corporate spy.",
    "Copy that. If this is another false alarm, I'm quitting.",
    "Roger. I dropped my gun in a puddle of bio-sludge.",
    "Understood. Please tell me this isn't another glitching android.",
    "Acknowledged. Are you sure? The GPS says that address doesn't exist anymore.",
    "Understood. Can you send the cleanup crew in advance?",
    "10-4. I'm going to need a bigger gun for this sector.",
    "Solid copy. I swear my radio is picking up ancient pop music.",
    "10-4. Can we get some air support on this?",
    "Acknowledged. I'm ignoring that last transmission, it sounded like a prank.",
    "Loud and clear. My partner just threw up. We might be delayed.",
    "Copy that. I think I'm hallucinating. Or the billboards are talking to me.",
    "Understood. I think my neural link is lagging.",
    "Understood. Did you hear that? Sounded like an explosion in Sector 7.",
    "Acknowledged. I'm going to need backup, and probably a mop.",
    "Roger. Tell the Chief I need a raise.",
    "Solid copy. I need a coffee break after this one.",
    "Understood. Are we getting hazard pay for this?",
    "Solid copy. I'm going to need a bigger gun for this sector.",
    "Acknowledged. My partner is asleep, I'm handling this alone.",
    "Solid copy. My dashcam is broken again, just so you know.",
    "Understood. My partner is asleep, I'm handling this alone.",
    "Solid copy. I'm pretty sure someone just tried to hack my steering wheel.",
    "Solid copy. Just passed a guy walking a robotic alligator.",
    "10-4. My hover-cruiser is making that weird noise again.",
    "Solid copy. Are you sure? The GPS says that address doesn't exist anymore.",
    "Understood. My stun baton is out of charge. I'll have to use harsh language.",
    "Understood. I'm ignoring that last transmission, it sounded like a prank.",
    "Roger. Can you repeat? A hover-train just went over my head.",
    "Copy that. My partner just threw up. We might be delayed.",
    "Acknowledged. I need a coffee break after this one.",
    "Solid copy. Please tell me this isn't another glitching android.",
    "Loud and clear. Are we getting hazard pay for this?",
    "Roger. I think my cruiser just became sentient. It's judging my driving.",
    "Copy that. I just saw a rat the size of a dog. I'm staying in the car.",
    "10-4. I'm currently stuck behind a garbage drone, give me a minute.",
    "Acknowledged. My stun baton is out of charge. I'll have to use harsh language.",
    "Loud and clear. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Solid copy. I'm not getting paid enough for this.",
    "Solid copy. My body armor is beeping, I think the battery is low.",
    "Roger. I think I'm hallucinating. Or the billboards are talking to me.",
    "Roger. Just passed a guy walking a robotic alligator.",
    "10-4. I think my comms are tapped by a corporate spy.",
    "Copy that. Did anyone else see that flash in the sky?",
    "Acknowledged. I think I'm hallucinating. Or the billboards are talking to me.",
    "Solid copy. Do we have any riot gear left in the armory?",
    "Acknowledged. My dashcam is broken again, just so you know.",
    "Loud and clear. My stun baton is out of charge. I'll have to use harsh language.",
    "Loud and clear. I just saw a rat the size of a dog. I'm staying in the car.",
    "10-4. I just spilled synth-caf all over my console.",
    "Acknowledged. Let's hope they don't have laser weapons this time.",
    "Loud and clear. Just passed a guy walking a robotic alligator.",
    "Acknowledged. Can you repeat? A hover-train just went over my head.",
    "Understood. Can we authorize lethal force just in case?",
    "Understood. My hover-cruiser is making that weird noise again.",
    "Copy that. I'm going to need backup, and probably a mop.",
    "Acknowledged. If this is another false alarm, I'm quitting.",
    "Solid copy. Did you hear that? Sounded like an explosion in Sector 7.",
    "Acknowledged. My partner just threw up. We might be delayed.",
    "10-4. Does anyone else smell burning plastic?",
    "Copy that. Can we get some air support on this?",
    "Solid copy. I just spilled synth-caf all over my console.",
    "Understood. I'm not getting paid enough for this.",
    "Roger. I think my neural link is lagging.",
    "Copy that. I'm not going in there without a hazmat suit.",
    "Copy that. I just spilled synth-caf all over my console.",
    "Copy that. Just passed a guy walking a robotic alligator.",
    "Loud and clear. Are you sure? The GPS says that address doesn't exist anymore.",
    "Roger. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Solid copy. I'm ignoring that last transmission, it sounded like a prank.",
    "Solid copy. My partner just threw up. We might be delayed.",
    "Understood. My cruiser's AC is blowing out neon smoke.",
    "Loud and clear. Do we have any riot gear left in the armory?",
    "Copy that. Wait, are we still under martial law?",
    "Copy that. My hover-cruiser is making that weird noise again.",
    "Loud and clear. I dropped my gun in a puddle of bio-sludge.",
    "Loud and clear. I'm going to need backup, and probably a mop.",
    "Copy that. Is it too late to request a desk job?",
    "Loud and clear. I'm taking my lunch break right after this.",
    "Copy that. Tell the Chief I need a raise.",
    "Solid copy. I just saw a rat the size of a dog. I'm staying in the car.",
    "Acknowledged. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Solid copy. Who designed these uniforms? They chafe.",
    "Loud and clear. Who designed these uniforms? They chafe.",
    "10-4. Who designed these uniforms? They chafe.",
    "Loud and clear. I just spilled synth-caf all over my console.",
    "Acknowledged. I just hit a pothole the size of a crater.",
    "Solid copy. My hover-cruiser is making that weird noise again.",
    "Understood. I think my comms are tapped by a corporate spy.",
    "10-4. I'm going to need backup, and probably a mop.",
    "Roger. Do we have any riot gear left in the armory?",
    "Acknowledged. I'm not getting paid enough for this.",
    "Loud and clear. I think I'm hallucinating. Or the billboards are talking to me.",
    "Understood. I think I'm hallucinating. Or the billboards are talking to me.",
    "Roger. Can you send the cleanup crew in advance?",
    "Loud and clear. I'm ignoring that last transmission, it sounded like a prank.",
    "Understood. Tell the Chief I need a raise.",
    "Loud and clear. Does anyone else smell burning plastic?",
    "Loud and clear. I need a coffee break after this one.",
    "Acknowledged. My cruiser's AC is blowing out neon smoke.",
    "Solid copy. My siren is jammed on the 'screaming banshee' setting.",
    "Acknowledged. My body armor is beeping, I think the battery is low.",
    "Understood. Does anyone else smell burning plastic?",
    "Loud and clear. Tell the Chief I need a raise.",
    "Understood. Who designed these uniforms? They chafe.",
    "Understood. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Solid copy. I'm going to need backup, and probably a mop.",
    "Copy that. My dashcam is broken again, just so you know.",
    "10-4. Wait, are we still under martial law?",
    "Solid copy. I just hit a pothole the size of a crater.",
    "Solid copy. I think my comms are tapped by a corporate spy.",
    "Acknowledged. Are we getting hazard pay for this?",
    "Understood. I'm not doing any more paperwork today, just saying.",
    "Loud and clear. Can we get some air support on this?",
    "Roger. Are you sure? The GPS says that address doesn't exist anymore.",
    "Acknowledged. Just passed a guy walking a robotic alligator.",
    "Acknowledged. I dropped my gun in a puddle of bio-sludge.",
    "10-4. I'm taking my lunch break right after this.",
    "Acknowledged. I think my cruiser just became sentient. It's judging my driving.",
    "Solid copy. Did anyone else see that flash in the sky?",
    "10-4. I just hit a pothole the size of a crater.",
    "Roger. Can we authorize lethal force just in case?",
    "Roger. I'm rerouting, the main bridge is currently on fire.",
    "10-4. I'm ignoring that last transmission, it sounded like a prank.",
    "Copy that. I think my cruiser just became sentient. It's judging my driving.",
    "Roger. Wait, are we still under martial law?",
    "10-4. I'm out of synthetic donuts, can someone bring me some?",
    "Acknowledged. I'm out of synthetic donuts, can someone bring me some?",
    "Understood. Are you sure? The GPS says that address doesn't exist anymore.",
    "Roger. I'm going to need backup, and probably a mop.",
    "10-4. I just saw a rat the size of a dog. I'm staying in the car.",
    "Copy that. My stun baton is out of charge. I'll have to use harsh language.",
    "Understood. Is it too late to request a desk job?",
    "Roger. Just don't send me back to the Gamma Slums.",
    "Solid copy. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "10-4. Is it too late to request a desk job?",
    "Copy that. My siren is jammed on the 'screaming banshee' setting.",
    "Loud and clear. My hover-cruiser is making that weird noise again.",
    "Solid copy. I'm currently stuck behind a garbage drone, give me a minute.",
    "Solid copy. I think I'm hallucinating. Or the billboards are talking to me.",
    "Loud and clear. I think my cruiser just became sentient. It's judging my driving.",
    "Acknowledged. I'm not going in there without a hazmat suit.",
    "Roger. I'm not going in there without a hazmat suit.",
    "Acknowledged. I think my comms are tapped by a corporate spy.",
    "Acknowledged. I think my neural link is lagging.",
    "Solid copy. I'm not doing any more paperwork today, just saying.",
    "Acknowledged. Please tell me this isn't another glitching android.",
    "Solid copy. I dropped my gun in a puddle of bio-sludge.",
    "Loud and clear. Just don't send me back to the Gamma Slums.",
    "Roger. My partner just threw up. We might be delayed.",
    "Understood. My dashcam is broken again, just so you know.",
    "Loud and clear. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Roger. Are we getting hazard pay for this?",
    "Understood. Can we get some air support on this?",
    "Roger. I'm not getting paid enough for this.",
    "Loud and clear. I'm pretty sure someone just tried to hack my steering wheel.",
    "Copy that. Can we authorize lethal force just in case?",
    "Loud and clear. I think my neural link is lagging.",
    "10-4. I'm not going in there without a hazmat suit.",
    "Roger. If this is another false alarm, I'm quitting.",
    "Roger. I'm ignoring that last transmission, it sounded like a prank.",
    "Acknowledged. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Roger. I'm taking my lunch break right after this.",
    "Solid copy. If this is another false alarm, I'm quitting.",
    "Understood. I need a coffee break after this one.",
    "Copy that. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "10-4. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Roger. My stun baton is out of charge. I'll have to use harsh language.",
    "10-4. My dashcam is broken again, just so you know.",
    "Acknowledged. Do we have any riot gear left in the armory?",
    "Understood. I think my cruiser just became sentient. It's judging my driving.",
    "10-4. Can you repeat? A hover-train just went over my head.",
    "Understood. I'm taking my lunch break right after this.",
    "Copy that. I'm out of synthetic donuts, can someone bring me some?",
    "Solid copy. Just don't send me back to the Gamma Slums.",
    "Roger. My hover-cruiser is making that weird noise again.",
    "Loud and clear. I'm going to need a bigger gun for this sector.",
    "Understood. I'm currently stuck behind a garbage drone, give me a minute.",
    "Copy that. My partner is asleep, I'm handling this alone.",
    "Solid copy. I'm taking my lunch break right after this.",
    "Understood. I'm going to need a bigger gun for this sector.",
    "Acknowledged. Wait, are we still under martial law?",
    "Loud and clear. I think my comms are tapped by a corporate spy.",
    "Loud and clear. I'm rerouting, the main bridge is currently on fire.",
    "Understood. If this is another false alarm, I'm quitting.",
    "10-4. If this is another false alarm, I'm quitting.",
    "10-4. I'm not getting paid enough for this.",
    "Copy that. Let's hope they don't have laser weapons this time.",
    "Acknowledged. Can you send the cleanup crew in advance?",
    "Copy that. I need a coffee break after this one.",
    "10-4. My partner just threw up. We might be delayed.",
    "Understood. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Understood. My body armor is beeping, I think the battery is low.",
    "Copy that. I'm currently stuck behind a garbage drone, give me a minute.",
    "Copy that. I'm not doing any more paperwork today, just saying.",
    "Roger. My body armor is beeping, I think the battery is low.",
    "Roger. I'm currently stuck behind a garbage drone, give me a minute.",
    "Solid copy. My stun baton is out of charge. I'll have to use harsh language.",
    "Understood. My siren is jammed on the 'screaming banshee' setting.",
    "Loud and clear. Can we authorize lethal force just in case?",
    "Solid copy. My cruiser's AC is blowing out neon smoke.",
    "10-4. I'm pretty sure someone just tried to hack my steering wheel.",
    "Loud and clear. Did you hear that? Sounded like an explosion in Sector 7.",
    "10-4. Can you send the cleanup crew in advance?",
    "Acknowledged. I'm rerouting, the main bridge is currently on fire.",
    "Solid copy. Let's hope they don't have laser weapons this time.",
    "Solid copy. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "10-4. Did you hear that? Sounded like an explosion in Sector 7.",
    "Solid copy. I'm not going in there without a hazmat suit.",
    "Solid copy. I think my cruiser just became sentient. It's judging my driving.",
    "Copy that. Does anyone else smell burning plastic?",
    "Loud and clear. My cruiser's AC is blowing out neon smoke.",
    "Copy that. Did you hear that? Sounded like an explosion in Sector 7.",
    "Understood. I'm pretty sure someone just tried to hack my steering wheel.",
    "Acknowledged. I just spilled synth-caf all over my console.",
    "Copy that. Are you sure? The GPS says that address doesn't exist anymore.",
    "Loud and clear. I'm not getting paid enough for this.",
    "Acknowledged. I'm taking my lunch break right after this.",
    "Roger. I just saw a rat the size of a dog. I'm staying in the car.",
    "Understood. My partner just threw up. We might be delayed.",
    "10-4. My body armor is beeping, I think the battery is low.",
    "Acknowledged. Can we authorize lethal force just in case?",
    "10-4. My partner is asleep, I'm handling this alone.",
    "Solid copy. Can you repeat? A hover-train just went over my head.",
    "10-4. Tell the Chief I need a raise.",
    "Copy that. Can you repeat? A hover-train just went over my head.",
    "Copy that. I'm taking my lunch break right after this.",
    "Loud and clear. Can you send the cleanup crew in advance?",
    "Acknowledged. Tell the Chief I need a raise.",
    "Copy that. I dropped my gun in a puddle of bio-sludge.",
    "10-4. Please tell me this isn't another glitching android.",
    "10-4. Can we authorize lethal force just in case?",
    "Roger. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Loud and clear. Did anyone else see that flash in the sky?",
    "Acknowledged. I'm not doing any more paperwork today, just saying.",
    "Roger. I'm out of synthetic donuts, can someone bring me some?",
    "Loud and clear. Let's hope they don't have laser weapons this time.",
    "10-4. I swear my radio is picking up ancient pop music.",
    "Acknowledged. My siren is jammed on the 'screaming banshee' setting.",
    "Acknowledged. Can we get some air support on this?",
    "10-4. Are we getting hazard pay for this?",
    "Understood. I'm rerouting, the main bridge is currently on fire.",
    "Copy that. Are we getting hazard pay for this?",
    "Roger. My dashcam is broken again, just so you know.",
    "Copy that. I'm rerouting, the main bridge is currently on fire.",
    "Acknowledged. Does anyone else smell burning plastic?",
    "Roger. Who designed these uniforms? They chafe.",
    "Acknowledged. Just don't send me back to the Gamma Slums.",
    "10-4. I think I'm hallucinating. Or the billboards are talking to me.",
    "Roger. Did you hear that? Sounded like an explosion in Sector 7.",
    "Understood. I'm not going in there without a hazmat suit.",
    "Loud and clear. I just hit a pothole the size of a crater.",
    "Loud and clear. I'm currently stuck behind a garbage drone, give me a minute.",
    "Roger. I'm going to need a bigger gun for this sector.",
    "Roger. I need a coffee break after this one.",
    "Copy that. Do we have any riot gear left in the armory?",
    "Roger. Is it too late to request a desk job?",
    "Copy that. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Loud and clear. My body armor is beeping, I think the battery is low.",
    "Loud and clear. If this is another false alarm, I'm quitting.",
    "Roger. I just spilled synth-caf all over my console.",
    "Understood. I swear my radio is picking up ancient pop music.",
    "Understood. Can you repeat? A hover-train just went over my head.",
    "Copy that. Please tell me this isn't another glitching android.",
    "Copy that. I'm ignoring that last transmission, it sounded like a prank.",
    "Roger. Please tell me this isn't another glitching android.",
    "Understood. Do we have any riot gear left in the armory?",
    "Understood. I just hit a pothole the size of a crater.",
    "10-4. I need a coffee break after this one.",
    "Copy that. I'm not getting paid enough for this.",
    "Loud and clear. Can you repeat? A hover-train just went over my head.",
    "Solid copy. Is it too late to request a desk job?",
    "Solid copy. Can we get some air support on this?",
    "Roger. My partner is asleep, I'm handling this alone.",
    "Roger. My cruiser's AC is blowing out neon smoke.",
    "Acknowledged. I swear my radio is picking up ancient pop music.",
    "Roger. Did anyone else see that flash in the sky?",
    "Solid copy. Are we getting hazard pay for this?",
    "Loud and clear. I'm not going in there without a hazmat suit.",
    "Roger. My siren is jammed on the 'screaming banshee' setting.",
    "10-4. My siren is jammed on the 'screaming banshee' setting.",
    "Understood. I just spilled synth-caf all over my console.",
    "10-4. Did anyone else see that flash in the sky?",
    "Understood. I just saw a rat the size of a dog. I'm staying in the car.",
    "10-4. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Acknowledged. I just saw a rat the size of a dog. I'm staying in the car.",
    "Solid copy. I think my neural link is lagging.",
    "Acknowledged. I'm going to need a bigger gun for this sector.",
    "Acknowledged. Is it too late to request a desk job?",
    "Roger. Can we get some air support on this?",
    "Solid copy. Tell the Chief I need a raise.",
    "10-4. I'm not doing any more paperwork today, just saying.",
    "Copy that. Can you send the cleanup crew in advance?",
    "Copy that. My body armor is beeping, I think the battery is low.",
    "Understood. I'm out of synthetic donuts, can someone bring me some?",
    "Copy that. Who designed these uniforms? They chafe.",
    "Loud and clear. I'm out of synthetic donuts, can someone bring me some?",
    "Copy that. I swear my radio is picking up ancient pop music.",
    "10-4. I'm rerouting, the main bridge is currently on fire.",
    "Loud and clear. My dashcam is broken again, just so you know.",
    "Understood. Just passed a guy walking a robotic alligator.",
    "10-4. Just passed a guy walking a robotic alligator."
];

window.handleDispatchChatReactions = function(text, reactionSender, senderUnit, typingDiv) {
    const lowerText = text.toLowerCase();
    const length = text.length;
    let isYelling = (text === text.toUpperCase() && text.match(/[A-Z]/));
    let isQuestion = text.trim().endsWith("?");

    let response = "";

    // 1. Tone Checks
    if (length > 150) {
        response = "Dispatch, keep it brief. We can't read a novel while driving.";
    } else if (isYelling) {
        response = "No need to shout over the radio, we hear you loud and clear.";
    } else if (isQuestion) {
        response = "I don't have an answer to that right now, Dispatch. We are a bit busy.";
    }
    
    // 2. Strict Intent Regex Checks (\\b for word boundaries)
    else if (/\\b(bored|boring)\\b/.test(lowerText)) {
        response = "If you're bored, you can come down here and do this paperwork.";
    } else if (/\\b(joke|funny)\\b/.test(lowerText)) {
        response = "Not the time for jokes, Dispatch. Focus on the comms.";
    } else if (/\\b(radio check|comms check)\\b/.test(lowerText)) {
        response = "Loud and clear, Dispatch. Signal is 5 by 5.";
    } else if (/\\b(order|orders|command)\\b/.test(lowerText)) {
        response = "We copy the orders. Proceeding as directed.";
    } else if (/\\b(thanks|thank you)\\b/.test(lowerText)) {
        response = "You're welcome, Dispatch. Just doing our jobs.";
    } else if (/\\b(hello|hi|hey)\\b/.test(lowerText)) {
        response = "Go ahead, Dispatch. We're listening.";
    } else {
        // Fallback
        response = fallbackReactions[Math.floor(Math.random() * fallbackReactions.length)];
    }

    typingDiv.querySelector('.text').innerHTML = response;

    // Multi-Officer Banter (40% chance another officer chimes in)
    if (Math.random() < 0.4 && typeof getActiveCallsigns === 'function') {
        const active = getActiveCallsigns();
        if (active.length > 1) {
            let secondSender = active[Math.floor(Math.random() * active.length)];
            while (secondSender === reactionSender && active.length > 1) {
                secondSender = active[Math.floor(Math.random() * active.length)];
            }
            
            setTimeout(() => {
                if (typeof addChatMessage === 'function') {
                    addChatMessage(secondSender, "I completely agree with that.", 'serious', false);
                }
            }, 3000 + Math.random() * 2000);
        }
    }
};
