const GLOBAL_GIBBERISH_RESPONSES = [
    "Dispatch, are you having a stroke? Repeat last transmission, you're making zero sense.",
    "10-9 Dispatch. We're getting heavy static. What did you say?",
    "Dispatch, I think someone sat on your keyboard.",
    "Copy that Dispatch... wait, no. Negative. What was that?",
    "Dispatch, please repeat. Your last transmission was complete garbage.",
    "Did you just smash your face into the console, Dispatch?",
    "10-9? I didn't catch a word of that.",
    "Dispatch, are you okay? Should we send a medic to the comms center?",
    "I literally have no idea what you just said, Dispatch.",
    "Please use standard codes, Dispatch. I can't read gibberish.",
    "Dispatch, your mic must be broken. It sounded like you sneezed while typing.",
    "Can anyone else understand what Dispatch just said?",
    "Dispatch, is there a cat walking across your keyboard?",
    "We need a translation on that, Dispatch.",
    "What the hell was that, Dispatch?",
    "Say again, Dispatch? You're coming over broken and unintelligible.",
    "Dispatch, did the system glitch? We got a string of nonsense.",
    "I'm assuming that was a typo, Dispatch.",
    "Dispatch, check your equipment. You're broadcasting garbage data.",
    "Are we under a cyber attack, Dispatch? What was that code?",
    "I'm going to pretend I didn't hear that, Dispatch.",
    "Dispatch, please clarify. You're speaking alien right now.",
    "If that was an order, Dispatch, I'm going to need you to repeat it in English.",
    "I think Dispatch needs a coffee break.",
    "Dispatch, you're 10-1 (unreadable). Repeat.",
    "Dispatch, my terminal just spit out random letters. Try again.",
    "What kind of 10-code is that, Dispatch?",
    "Dispatch, are you drunk? We can't understand you.",
    "Can you repeat that slowly, Dispatch?",
    "Dispatch, please stop messing around on the comms.",
    "Dispatch, this is a secure channel. Use it properly.",
    "Is someone holding you hostage, Dispatch? Blink twice.",
    "Dispatch, I'm logging that as a transmission error.",
    "Can someone go check on Dispatch?",
    "Dispatch, are you falling asleep at the desk?",
    "10-4 on the... whatever that was.",
    "Dispatch, my translation software just crashed trying to read that.",
    "Are you trying to speak in tongues, Dispatch?",
    "Dispatch, if you're having an emergency, send a 10-33.",
    "I don't think that's a valid sector, Dispatch.",
    "Dispatch, please confirm you are conscious.",
    "Did you drop your radio, Dispatch?",
    "Dispatch, I think your terminal is possessed.",
    "We read you zero by zero, Dispatch. Completely unreadable.",
    "Dispatch, clear your throat and try again.",
    "I'm not even going to try to decipher that, Dispatch.",
    "Dispatch, is the new rookie on the console again?",
    "Dispatch, you hit send too early.",
    "I think Dispatch's neural-link just shorted out.",
    "Dispatch, please reset your terminal. It's sending corrupted data.",
    "What? You're making zero sense.",
    "What? We can't read you.",
    "Repeat that. Are you okay?",
    "Say again. Is someone on your keyboard?",
    "10-9 Dispatch. We need a translation.",
    "10-9 Dispatch. You're making zero sense.",
    "Dispatch, Are you okay?",
    "What? Your transmission is garbage.",
    "Say again. You're making zero sense.",
    "Say again. That was unintelligible.",
    "Dispatch, Your transmission is garbage.",
    "10-9 Dispatch. Stop messing around.",
    "What? Is someone on your keyboard?",
    "10-9 Dispatch. Are you okay?",
    "Dispatch, Is someone on your keyboard?",
    "10-9 Dispatch. Your transmission is garbage.",
    "Repeat that. We need a translation.",
    "Dispatch, Stop messing around.",
    "Dispatch, You're making zero sense.",
    "What? Stop messing around.",
    "Repeat that. Stop messing around.",
    "Repeat that. Your transmission is garbage.",
    "10-9 Dispatch. We can't read you.",
    "10-9 Dispatch. That was unintelligible.",
    "Say again. Stop messing around.",
    "Dispatch, We need a translation.",
    "Dispatch, That was unintelligible.",
    "Dispatch, We can't read you.",
    "Say again. We can't read you.",
    "What? We need a translation.",
    "Repeat that. You're making zero sense.",
    "What? That was unintelligible.",
    "Repeat that. That was unintelligible.",
    "Say again. Your transmission is garbage.",
    "Repeat that. Is someone on your keyboard?",
    "Say again. We need a translation.",
    "Dispatch, Check your equipment.",
    "10-9 Dispatch. Check your equipment.",
    "What? Are you okay?",
    "Say again. Are you okay?",
    "Say again. Check your equipment.",
    "Repeat that. We can't read you.",
    "10-9 Dispatch. Is someone on your keyboard?",
    "Repeat that. Check your equipment.",
    "What? Check your equipment.",
];

