
const GLOBAL_ARRIVING_CHATS_STANDARD = [
    "On my way to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "Show me responding to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR%. See you there. [+15 POINTS]",
    "On my way to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "Show me responding to Sector %SECTOR%. See you there. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR%. See you there. [+15 POINTS]",
    "On my way to Sector %SECTOR%. See you there. [+15 POINTS]",
    "On my way to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "Show me responding to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR% now. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR% now. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "Show me responding to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "Show me responding to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR%. See you there. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "Show me responding to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR% now. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR%. See you there. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "Show me responding to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR% now. [+15 POINTS]",
    "On my way to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "On my way to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "On my way to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR% now. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR% now. [+15 POINTS]",
    "On my way to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR%. See you there. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR% now. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR%. See you there. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR% now. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "On my way to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "Acknowledged, rolling out to Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR%. See you there. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR%. I'm right around the corner. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "I have the call. Heading to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "Show me responding to Sector %SECTOR%. ETA 3 minutes. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR% to engage the call. [+15 POINTS]",
    "On my way to Sector %SECTOR% now. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR%. Stepping on it. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "Moving to intercept at Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "Show me responding to Sector %SECTOR% now. [+15 POINTS]",
    "Dispatch, I'm inbound to Sector %SECTOR%. See you there. [+15 POINTS]",
    "Show me responding to Sector %SECTOR%. Activating lights and sirens. [+15 POINTS]",
    "10-4, en route to Sector %SECTOR%. Keep the channel clear. [+15 POINTS]",
    "Copy that Dispatch, pushing to Sector %SECTOR% to engage the call. [+15 POINTS]",
    "Roger that. Responding to Sector %SECTOR%. Will update when on scene. [+15 POINTS]",
    "I'm mobile, heading to Sector %SECTOR%. Requesting updates as I approach. [+15 POINTS]"
];

const GLOBAL_ARRIVING_CHATS_PANIC = [
    "All units hold! I am arriving at the 10-99! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! [+500 POINTS]",
    "I'm here! Engaging the 10-99! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! [+500 POINTS]",
    "I'm here! Engaging the 10-99! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! [+500 POINTS]",
    "I'm here! Engaging the 10-99! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Let's do this! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! EMS standby! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Need backup! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Requesting air support! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! Let's do this! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Let's do this! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Requesting air support! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Moving in! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Securing the perimeter! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! EMS standby! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Suspects everywhere! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Let's do this! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Taking fire! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Setting up a blockade! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Need backup! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! Suspects everywhere! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Setting up a blockade! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! Setting up a blockade! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Securing the perimeter! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! Moving in! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Moving in! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! Securing the perimeter! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Requesting air support! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! Heavily armed! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! Taking fire! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Need backup! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Taking fire! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! EMS standby! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Taking fire! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Heavily armed! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! EMS standby! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Securing the perimeter! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! Need backup! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Need backup! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Taking fire! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Requesting air support! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! EMS standby! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Moving in! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Moving in! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Heavily armed! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! Setting up a blockade! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! Taking fire! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Need backup! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! Need backup! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Securing the perimeter! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Suspects everywhere! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Taking fire! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! Let's do this! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Moving in! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Securing the perimeter! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! Need backup! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! Taking fire! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Setting up a blockade! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Setting up a blockade! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Securing the perimeter! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Let's do this! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Taking fire! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Securing the perimeter! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Suspects everywhere! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Securing the perimeter! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Taking fire! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Securing the perimeter! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Taking fire! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Requesting air support! [+500 POINTS]",
    "10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Suspects everywhere! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! Taking fire! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Heavily armed! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Requesting air support! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Need backup! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Let's do this! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Let's do this! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Taking fire! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Securing the perimeter! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! EMS standby! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Suspects everywhere! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Requesting air support! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Heavily armed! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! Requesting air support! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Suspects everywhere! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Heavily armed! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! Let's do this! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Moving in! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Requesting air support! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Requesting air support! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! EMS standby! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! EMS standby! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Setting up a blockade! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Let's do this! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Setting up a blockade! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! EMS standby! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! Setting up a blockade! [+500 POINTS]",
    "Dispatch, show me 10-23 at the 10-99! Engaging! Suspects everywhere! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Setting up a blockade! [+500 POINTS]",
    "Arrived at the 10-99! I need backup right now! Need backup! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Taking fire! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Let's do this! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Requesting air support! [+500 POINTS]",
    "I'm on scene for the 10-99! It's a warzone! Heavily armed! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Taking fire! [+500 POINTS]",
    "I'm at the 10-99 location! Weapons hot! Taking fire! [+500 POINTS]",
    "Dispatch, 10-99 received! I'm on scene! Moving in! [+500 POINTS]",
    "I'm here! Engaging the 10-99! Let's do this! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Need backup! [+500 POINTS]",
    "Engaging 10-99! Suspects in sight! Need backup! [+500 POINTS]",
    "All units hold! I am arriving at the 10-99! Suspects everywhere! [+500 POINTS]",
    "10-99 in progress! I'm on site and moving in! Taking fire! [+500 POINTS]"
];
