
const GLOBAL_ARRIVING_CHATS_STANDARD = [
    `On my way to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `Show me responding to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `10-4, en route to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector}. See you there. [+15 POINTS]`,
    `On my way to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector} to engage the call. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `Show me responding to Sector ${sector}. See you there. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector}. See you there. [+15 POINTS]`,
    `On my way to Sector ${sector}. See you there. [+15 POINTS]`,
    `On my way to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector} to engage the call. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector} to engage the call. [+15 POINTS]`,
    `Show me responding to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector} now. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector} to engage the call. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector} now. [+15 POINTS]`,
    `10-4, en route to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `Show me responding to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `Show me responding to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector}. See you there. [+15 POINTS]`,
    `10-4, en route to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `10-4, en route to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `Show me responding to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector} now. [+15 POINTS]`,
    `10-4, en route to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector}. See you there. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `10-4, en route to Sector ${sector} to engage the call. [+15 POINTS]`,
    `Show me responding to Sector ${sector} to engage the call. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector} now. [+15 POINTS]`,
    `On my way to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `On my way to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `On my way to Sector ${sector} to engage the call. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector} now. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector} now. [+15 POINTS]`,
    `On my way to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector}. See you there. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector} now. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector}. See you there. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `10-4, en route to Sector ${sector} now. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `On my way to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `Acknowledged, rolling out to Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `10-4, en route to Sector ${sector}. See you there. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector}. I'm right around the corner. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `I have the call. Heading to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `Show me responding to Sector ${sector}. ETA 3 minutes. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector} to engage the call. [+15 POINTS]`,
    `On my way to Sector ${sector} now. [+15 POINTS]`,
    `10-4, en route to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector}. Stepping on it. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector} to engage the call. [+15 POINTS]`,
    `Moving to intercept at Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `Show me responding to Sector ${sector} now. [+15 POINTS]`,
    `Dispatch, I'm inbound to Sector ${sector}. See you there. [+15 POINTS]`,
    `Show me responding to Sector ${sector}. Activating lights and sirens. [+15 POINTS]`,
    `10-4, en route to Sector ${sector}. Keep the channel clear. [+15 POINTS]`,
    `Copy that Dispatch, pushing to Sector ${sector} to engage the call. [+15 POINTS]`,
    `Roger that. Responding to Sector ${sector}. Will update when on scene. [+15 POINTS]`,
    `I'm mobile, heading to Sector ${sector}. Requesting updates as I approach. [+15 POINTS]`
];

const GLOBAL_ARRIVING_CHATS_PANIC = [
    `All units hold! I am arriving at the 10-99! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Let's do this! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! EMS standby! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Need backup! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Requesting air support! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! Let's do this! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Let's do this! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Requesting air support! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Moving in! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Securing the perimeter! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! EMS standby! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Suspects everywhere! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Let's do this! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Taking fire! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Setting up a blockade! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Need backup! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! Suspects everywhere! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Setting up a blockade! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! Setting up a blockade! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Securing the perimeter! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! Moving in! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Moving in! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! Securing the perimeter! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Requesting air support! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! Heavily armed! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! Taking fire! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Need backup! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Taking fire! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! EMS standby! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Taking fire! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Heavily armed! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! EMS standby! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Securing the perimeter! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! Need backup! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Need backup! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Taking fire! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Requesting air support! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! EMS standby! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Moving in! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Moving in! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Heavily armed! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! Setting up a blockade! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! Taking fire! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Need backup! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! Need backup! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Securing the perimeter! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Suspects everywhere! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Taking fire! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! Let's do this! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Moving in! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Securing the perimeter! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! Need backup! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! Taking fire! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Setting up a blockade! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Setting up a blockade! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Securing the perimeter! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Let's do this! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Taking fire! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Securing the perimeter! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Suspects everywhere! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Securing the perimeter! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Taking fire! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Securing the perimeter! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Taking fire! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Requesting air support! [+500 POINTS]`,
    `10-4 Dispatch, I am engaging the 10-99 and arriving on scene! Suspects everywhere! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! Taking fire! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Heavily armed! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Requesting air support! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Need backup! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Let's do this! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Let's do this! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Taking fire! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Securing the perimeter! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! EMS standby! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Suspects everywhere! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Requesting air support! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Heavily armed! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! Requesting air support! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Suspects everywhere! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Heavily armed! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! Let's do this! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Moving in! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Requesting air support! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Requesting air support! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! EMS standby! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! EMS standby! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Setting up a blockade! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Let's do this! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Setting up a blockade! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! EMS standby! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! Setting up a blockade! [+500 POINTS]`,
    `Dispatch, show me 10-23 at the 10-99! Engaging! Suspects everywhere! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Setting up a blockade! [+500 POINTS]`,
    `Arrived at the 10-99! I need backup right now! Need backup! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Taking fire! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Let's do this! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Requesting air support! [+500 POINTS]`,
    `I'm on scene for the 10-99! It's a warzone! Heavily armed! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Taking fire! [+500 POINTS]`,
    `I'm at the 10-99 location! Weapons hot! Taking fire! [+500 POINTS]`,
    `Dispatch, 10-99 received! I'm on scene! Moving in! [+500 POINTS]`,
    `I'm here! Engaging the 10-99! Let's do this! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Need backup! [+500 POINTS]`,
    `Engaging 10-99! Suspects in sight! Need backup! [+500 POINTS]`,
    `All units hold! I am arriving at the 10-99! Suspects everywhere! [+500 POINTS]`,
    `10-99 in progress! I'm on site and moving in! Taking fire! [+500 POINTS]`
];
