
const GLOBAL_ARRESTING_CHATS = [
    `{suspectStr} didn't put up a fight. Another one off the streets.`,
    `{suspectStr} surrendered. Suspect is cooperative.`,
    `In custody. {suspectStr} is heading to booking. Secured.`,
    `Got the bracelets on {suspectStr}. Easiest collar of the day.`,
    `{suspectStr} is reading their rights now. I'm going to need a coffee after this.`,
    `Bagged {suspectStr}. See you back at the station.`,
    `{suspectStr} is reading their rights now. Scene is clear.`,
    `Suspect {suspectStr} complied with orders. In custody. No injuries.`,
    `I've got {suspectStr} in the back. See you back at the station.`,
    `{suspectStr} is detained. Paperwork is gonna be a nightmare.`,
    `Suspect {suspectStr} is secure. Suspect is whining about the cuffs.`,
    `Handcuffed and secured. {suspectStr} is in the back of my cruiser. See you back at the station.`,
    `{suspectStr} didn't put up a fight. Show me 10-8 from this.`,
    `Target {suspectStr} apprehended. All units can stand down.`,
    `I've got {suspectStr} in the back. Suspect is whining about the cuffs.`,
    `Got the bracelets on {suspectStr}. See you back at the station.`,
    `Wrapping it up here. {suspectStr} is cuffed. Reading them the riot act.`,
    `Got the bracelets on {suspectStr}. Another one off the streets.`,
    `Handcuffed and secured. {suspectStr} is in the back of my cruiser. Suspect is whining about the cuffs.`,
    `Suspect {suspectStr} gave up easy. Secured.`,
    `Situation resolved. {suspectStr} is under arrest. Moving to clear the intersection.`,
    `Target {suspectStr} in custody. Suspect wants a lawyer.`,
    `{suspectStr} is detained. Easiest collar of the day.`,
    `In custody. {suspectStr} is heading to booking. Show me 10-8 from this.`,
    `{suspectStr} secured. Reading them the riot act.`,
    `{suspectStr} secured. Show me 10-8 from this.`,
    `{suspectStr} didn't put up a fight. No injuries.`,
    `I arrested {suspectStr}. Easiest collar of the day.`,
    `I arrested {suspectStr}. We're 10-8.`,
    `I've got {suspectStr} in the back. All units can stand down.`,
    `Suspect {suspectStr} gave up easy. See you back at the station.`,
    `Arrest successful on {suspectStr}. Reading them the riot act.`,
    `Suspect {suspectStr} gave up easy. Taking them to booking.`,
    `Situation resolved. {suspectStr} is under arrest. Returning to precinct.`,
    `Apprehended {suspectStr} without incident. I'll need a tow truck later, but we're Code 4.`,
    `We have {suspectStr} in custody. Returning to precinct.`,
    `Suspect {suspectStr} gave up easy. Code 4.`,
    `Bagged {suspectStr}. Paperwork is gonna be a nightmare.`,
    `Arrest successful on {suspectStr}. All units can stand down.`,
    `Handcuffed and secured. {suspectStr} is in the back of my cruiser. Suspect is cooperative.`,
    `Target {suspectStr} apprehended. Resume normal traffic.`,
    `I arrested {suspectStr}. No injuries.`,
    `Suspect {suspectStr} is secure. Paperwork is gonna be a nightmare.`,
    `Code 4, {suspectStr} is detained. Suspect wants a lawyer.`,
    `Bagged {suspectStr}. Transporting to central.`,
    `Target {suspectStr} apprehended. Returning to precinct.`,
    `In custody. {suspectStr} is heading to booking. Taking them to booking.`,
    `Secured {suspectStr} without a scuffle. Scene is clear.`,
    `{suspectStr} is detained. They'll be doing time for this.`,
    `Suspect {suspectStr} complied with orders. In custody. Secured.`,
    `We have {suspectStr} in custody. Reading them the riot act.`,
    `Apprehended {suspectStr} without incident. They didn't even try to run.`,
    `Got them. {suspectStr} is in cuffs. Scene is clear.`,
    `Code 4, {suspectStr} is detained. See you back at the station.`,
    `{suspectStr} surrendered. Suspect wants a lawyer.`,
    `Suspect {suspectStr} is secure. We're 10-8.`,
    `I've got {suspectStr} in the back. I'm going to need a coffee after this.`,
    `Apprehended {suspectStr} without incident. Resume normal traffic.`,
    `{suspectStr} didn't put up a fight. I'm going to need a coffee after this.`,
    `{suspectStr} surrendered. Moving to clear the intersection.`,
    `{suspectStr} is detained. Another one off the streets.`,
    `Target {suspectStr} in custody. Reading them the riot act.`,
    `Suspect {suspectStr} is secure. Code 4.`,
    `Got them. {suspectStr} is in cuffs. Transporting to central.`,
    `Target {suspectStr} apprehended. We're 10-8.`,
    `Situation resolved. {suspectStr} is under arrest. Taking them to booking.`,
    `Got them. {suspectStr} is in cuffs. Suspect is cooperative.`,
    `Got them. {suspectStr} is in cuffs. They didn't even try to run.`,
    `{suspectStr} is detained. We're 10-8.`,
    `We have {suspectStr} in custody. Suspect is whining about the cuffs.`,
    `I've got {suspectStr} in the back. We're 10-8.`,
    `Handcuffed and secured. {suspectStr} is in the back of my cruiser. All units can stand down.`,
    `{suspectStr} is detained. Reading them the riot act.`,
    `Got them. {suspectStr} is in cuffs. Resume normal traffic.`,
    `Secured {suspectStr} without a scuffle. Suspect wants a lawyer.`,
    `Suspect {suspectStr} complied with orders. In custody. Suspect wants a lawyer.`,
    `Suspect {suspectStr} complied with orders. In custody. All units can stand down.`,
    `Suspect {suspectStr} gave up easy. Transporting to central.`,
    `Suspect {suspectStr} is secure. Taking them to booking.`,
    `Target {suspectStr} in custody. Show me 10-8 from this.`,
    `In custody. {suspectStr} is heading to booking. Reading them the riot act.`,
    `Situation resolved. {suspectStr} is under arrest. Code 4.`,
    `Code 4. {suspectStr} is going away for a long time. I'll need a tow truck later, but we're Code 4.`,
    `Secured {suspectStr} without a scuffle. No injuries.`,
    `Target {suspectStr} in custody. Wrapping up here.`,
    `{suspectStr} is detained. See you back at the station.`,
    `Target {suspectStr} apprehended. Moving to clear the intersection.`,
    `Code 4. {suspectStr} is going away for a long time. Another one off the streets.`,
    `Arrest successful on {suspectStr}. Taking them to booking.`,
    `Handcuffed and secured. {suspectStr} is in the back of my cruiser. Resume normal traffic.`,
    `Suspect {suspectStr} gave up easy. Resume normal traffic.`,
    `{suspectStr} secured. We're 10-8.`,
    `Got them. {suspectStr} is in cuffs. Easiest collar of the day.`,
    `We have {suspectStr} in custody. Moving to clear the intersection.`,
    `In custody. {suspectStr} is heading to booking. Code 4.`,
    `Target {suspectStr} in custody. Transporting to central.`,
    `{suspectStr} secured. Resume normal traffic.`,
    `{suspectStr} surrendered. See you back at the station.`,
    `Suspect {suspectStr} is secure. See you back at the station.`,
    `We have {suspectStr} in custody. I'm going to need a coffee after this.`,
    `I arrested {suspectStr}. Suspect is cooperative.`,
    `Suspect {suspectStr} is secure. They'll be doing time for this.`,
    `Arrest successful on {suspectStr}. See you back at the station.`,
    `{suspectStr} secured. I'll need a tow truck later, but we're Code 4.`,
    `Got the bracelets on {suspectStr}. Wrapping up here.`,
    `Target {suspectStr} apprehended. Transporting to central.`,
    `I've got {suspectStr} in the back. Easiest collar of the day.`,
    `{suspectStr} secured. Taking them to booking.`,
    `Target {suspectStr} in custody. All units can stand down.`,
    `{suspectStr} surrendered. Resume normal traffic.`,
    `Bagged {suspectStr}. They didn't even try to run.`,
    `Suspect {suspectStr} is secure. Returning to precinct.`,
    `Code 4. {suspectStr} is going away for a long time. Show me 10-8 from this.`,
    `Target {suspectStr} apprehended. Taking them to booking.`,
    `Suspect {suspectStr} gave up easy. Moving to clear the intersection.`,
    `Arrest successful on {suspectStr}. Transporting to central.`,
    `Got them. {suspectStr} is in cuffs. I'm going to need a coffee after this.`,
    `We have {suspectStr} in custody. Scene is clear.`,
    `Target {suspectStr} in custody. I'll need a tow truck later, but we're Code 4.`,
    `{suspectStr} didn't put up a fight. Secured.`,
    `{suspectStr} surrendered. Returning to precinct.`,
    `{suspectStr} is reading their rights now. Easiest collar of the day.`,
    `Suspect {suspectStr} is secure. Suspect is cooperative.`,
    `In custody. {suspectStr} is heading to booking. No injuries.`,
    `Suspect {suspectStr} is secure. Another one off the streets.`,
    `Got them. {suspectStr} is in cuffs. Wrapping up here.`,
    `Suspect {suspectStr} complied with orders. In custody. Show me 10-8 from this.`,
    `Situation resolved. {suspectStr} is under arrest. They'll be doing time for this.`,
    `{suspectStr} secured. See you back at the station.`,
    `Code 4. {suspectStr} is going away for a long time. Returning to precinct.`,
    `I arrested {suspectStr}. Paperwork is gonna be a nightmare.`,
    `Apprehended {suspectStr} without incident. Taking them to booking.`,
    `I've got {suspectStr} in the back. Code 4.`,
    `Wrapping it up here. {suspectStr} is cuffed. They didn't even try to run.`,
    `{suspectStr} secured. Another one off the streets.`,
    `Code 4, {suspectStr} is detained. I'm going to need a coffee after this.`
];

const GLOBAL_KILLING_CHATS = [
    `Threat eliminated. They made their choice.`,
    `Suspect {suspectStr} eliminated. No survivors. Returning to patrol.`,
    `Suspect {suspectStr} eliminated. Send bio-hazard cleanup to our coordinates.`,
    `I put {suspectStr} down. No survivors. Returning to patrol.`,
    `Suspect {suspectStr} is deceased. Suspect didn't stand a chance.`,
    `Suspect {suspectStr} eliminated. I'm 10-8, but send cleanup.`,
    `I ended it. {suspectStr} is down. Call the meat wagon.`,
    `Target {suspectStr} was hostile. Problem solved permanently. EMS is too late for this one.`,
    `{suspectStr} chose the hard way. Need a supervisor on scene.`,
    `Target {suspectStr} was hostile. Problem solved permanently. Let the morgue know they have an incoming.`,
    `I put {suspectStr} down. Let the morgue know they have an incoming.`,
    `{suspectStr} pulled a weapon. Messy out here.`,
    `Code 4. {suspectStr} is no longer a threat. No survivors. Returning to patrol.`,
    `Suspect {suspectStr} eliminated. Taking a breath. Scene is secure.`,
    `{suspectStr} dropped. Taking a breath. Scene is secure.`,
    `Suspect {suspectStr} KIA. Taking a breath. Scene is secure.`,
    `{suspectStr} resisted. Lethal force applied. Waiting for crime scene investigators.`,
    `Target {suspectStr} neutralized. Area is red but quiet.`,
    `Target {suspectStr} neutralized. Messy out here.`,
    `Target {suspectStr} took two to the chest. Area is red but quiet.`,
    `Suspect {suspectStr} KIA. Filing report now.`,
    `{suspectStr} dropped. It was self defense.`,
    `{suspectStr} pulled a weapon. Taking a breath. Scene is secure.`,
    `Hostile down. {suspectStr} is dead. Area is red but quiet.`,
    `Engaged {suspectStr}. Suspect is dead. Filing report now.`,
    `Code 4. {suspectStr} is no longer a threat. Taking a breath. Scene is secure.`,
    `Had to use lethal on {suspectStr}. EMS is too late for this one.`,
    `Suspect {suspectStr} is deceased. Taking a breath. Scene is secure.`,
    `Target {suspectStr} was hostile. Problem solved permanently. I'm 10-8, but send cleanup.`,
    `Target {suspectStr} was hostile. Problem solved permanently. Suspect didn't stand a chance.`,
    `{suspectStr} chose the hard way. Going to be a lot of paperwork.`,
    `Fatal outcome for {suspectStr}. Let the morgue know they have an incoming.`,
    `{suspectStr} dropped. Standing by for homicide detectives.`,
    `{suspectStr} resisted. Lethal force applied. Filing report now.`,
    `Suspect {suspectStr} KIA. Area is red but quiet.`,
    `Threat eliminated. Taking a breath. Scene is secure.`,
    `{suspectStr} resisted. Lethal force applied. Send bio-hazard cleanup to our coordinates.`,
    `Suspect {suspectStr} KIA. Need a supervisor on scene.`,
    `{suspectStr} dropped. I'm 10-8, but send cleanup.`,
    `{suspectStr} pulled a weapon. Let the morgue know they have an incoming.`,
    `Code 4. {suspectStr} is no longer a threat. Send bio-hazard cleanup to our coordinates.`,
    `Target {suspectStr} neutralized. Need a supervisor on scene.`,
    `I ended it. {suspectStr} is down. Send the coroner.`,
    `{suspectStr} resisted. Lethal force applied. I'm 10-8, but send cleanup.`,
    `Suspect {suspectStr} is deceased. Let the morgue know they have an incoming.`,
    `Target {suspectStr} neutralized. Going to be a lot of paperwork.`,
    `Target {suspectStr} took two to the chest. Call the meat wagon.`,
    `I put {suspectStr} down. I'm 10-8, but send cleanup.`,
    `Target {suspectStr} neutralized. Call the meat wagon.`,
    `Suspect {suspectStr} KIA. I need a union rep.`,
    `Hostile down. {suspectStr} is dead. Code 4. Secure the perimeter.`,
    `Code 4. {suspectStr} is no longer a threat. I need a union rep.`,
    `Had to use lethal on {suspectStr}. Send bio-hazard cleanup to our coordinates.`,
    `{suspectStr} chose the hard way. It was self defense.`,
    `{suspectStr} dropped. Going to be a lot of paperwork.`,
    `Fatal outcome for {suspectStr}. Filing report now.`,
    `{suspectStr} tried to fire at me. It was self defense.`,
    `I ended it. {suspectStr} is down. Going to be a lot of paperwork.`,
    `Suspect {suspectStr} eliminated. Code 4. Secure the perimeter.`,
    `I put {suspectStr} down. Send the coroner.`,
    `Suspect {suspectStr} KIA. Send bio-hazard cleanup to our coordinates.`,
    `{suspectStr} pulled a weapon. Filing report now.`,
    `{suspectStr} tried to fire at me. Let the morgue know they have an incoming.`,
    `{suspectStr} pulled a weapon. Need a supervisor on scene.`,
    `I ended it. {suspectStr} is down. Need a supervisor on scene.`,
    `Code 4. {suspectStr} is no longer a threat. Call the meat wagon.`,
    `{suspectStr} dropped. Let the morgue know they have an incoming.`,
    `{suspectStr} pulled a weapon. Waiting for crime scene investigators.`,
    `{suspectStr} tried to fire at me. Send bio-hazard cleanup to our coordinates.`,
    `{suspectStr} dropped. They made their choice.`,
    `Suspect {suspectStr} is deceased. No survivors. Returning to patrol.`,
    `Engaged {suspectStr}. Suspect is dead. It was self defense.`,
    `{suspectStr} pulled a weapon. It was self defense.`,
    `Suspect {suspectStr} is deceased. EMS is too late for this one.`,
    `Fatal outcome for {suspectStr}. Send the coroner.`,
    `Hostile down. {suspectStr} is dead. Going to be a lot of paperwork.`,
    `Suspect {suspectStr} is deceased. Filing report now.`,
    `{suspectStr} chose the hard way. Send bio-hazard cleanup to our coordinates.`,
    `Suspect {suspectStr} eliminated. Going to be a lot of paperwork.`,
    `Target {suspectStr} neutralized. EMS is too late for this one.`,
    `{suspectStr} tried to fire at me. Standing by for homicide detectives.`,
    `Suspect {suspectStr} eliminated. Standing by for homicide detectives.`,
    `Engaged {suspectStr}. Suspect is dead. Waiting for crime scene investigators.`,
    `Fatal outcome for {suspectStr}. Suspect didn't stand a chance.`,
    `Suspect {suspectStr} eliminated. Need a supervisor on scene.`,
    `Suspect {suspectStr} eliminated. Let the morgue know they have an incoming.`,
    `Target {suspectStr} was hostile. Problem solved permanently. Taking a breath. Scene is secure.`,
    `I put {suspectStr} down. Messy out here.`,
    `Target {suspectStr} took two to the chest. EMS is too late for this one.`,
    `Suspect {suspectStr} KIA. Call the meat wagon.`,
    `{suspectStr} dropped. Area is red but quiet.`,
    `{suspectStr} chose the hard way. I'm 10-8, but send cleanup.`,
    `Had to use lethal on {suspectStr}. Let the morgue know they have an incoming.`,
    `{suspectStr} tried to fire at me. Waiting for crime scene investigators.`,
    `{suspectStr} chose the hard way. They made their choice.`,
    `Had to use lethal on {suspectStr}. Messy out here.`,
    `Target {suspectStr} took two to the chest. Waiting for crime scene investigators.`,
    `Suspect {suspectStr} eliminated. I need a union rep.`,
    `Engaged {suspectStr}. Suspect is dead. No survivors. Returning to patrol.`,
    `{suspectStr} resisted. Lethal force applied. EMS is too late for this one.`,
    `Suspect {suspectStr} eliminated. Filing report now.`,
    `{suspectStr} pulled a weapon. They made their choice.`,
    `Hostile down. {suspectStr} is dead. EMS is too late for this one.`,
    `Subject down. Taking a breath. Scene is secure.`,
    `{suspectStr} tried to fire at me. Messy out here.`,
    `Had to use lethal on {suspectStr}. They made their choice.`,
    `{suspectStr} tried to fire at me. Need a supervisor on scene.`,
    `I ended it. {suspectStr} is down. EMS is too late for this one.`,
    `Suspect {suspectStr} KIA. Waiting for crime scene investigators.`,
    `{suspectStr} resisted. Lethal force applied. They made their choice.`,
    `Engaged {suspectStr}. Suspect is dead. Messy out here.`,
    `Subject down. EMS is too late for this one.`,
    `Had to use lethal on {suspectStr}. Going to be a lot of paperwork.`,
    `Fatal outcome for {suspectStr}. Call the meat wagon.`,
    `Fatal outcome for {suspectStr}. Code 4. Secure the perimeter.`,
    `{suspectStr} dropped. Messy out here.`,
    `I ended it. {suspectStr} is down. I'm 10-8, but send cleanup.`,
    `Suspect {suspectStr} eliminated. Messy out here.`,
    `Engaged {suspectStr}. Suspect is dead. Taking a breath. Scene is secure.`,
    `Subject down. I need a union rep.`,
    `Suspect {suspectStr} eliminated. It was self defense.`,
    `I put {suspectStr} down. Filing report now.`,
    `Suspect {suspectStr} KIA. I'm 10-8, but send cleanup.`,
    `Suspect {suspectStr} is deceased. Going to be a lot of paperwork.`,
    `Hostile down. {suspectStr} is dead. I need a union rep.`,
    `Target {suspectStr} neutralized. Filing report now.`,
    `{suspectStr} resisted. Lethal force applied. Taking a breath. Scene is secure.`,
    `I ended it. {suspectStr} is down. Area is red but quiet.`,
    `Suspect {suspectStr} is deceased. Send bio-hazard cleanup to our coordinates.`,
    `Fatal outcome for {suspectStr}. Area is red but quiet.`,
    `Hostile down. {suspectStr} is dead. Send the coroner.`,
    `Threat eliminated. Need a supervisor on scene.`,
    `{suspectStr} chose the hard way. Messy out here.`,
    `Suspect {suspectStr} is deceased. Call the meat wagon.`,
    `Fatal outcome for {suspectStr}. I need a union rep.`,
    `{suspectStr} chose the hard way. Suspect didn't stand a chance.`
];
