// ==========================================
// MASSIVE NPC PERSONALITY ENGINE v3
// ==========================================
// Handles highly realistic reactions based on word boundaries, tone, length, and content.

const fallbackReactions = [
    "10-4. Copy.",
    "Roger that, Dispatch.",
    "Loud and clear.",
    "Copy. Patrol continuing.",
    "Understood.",
    "Solid copy.",
    "10-4, showing en route.",
    "Acknowledged.",
    "Copy that. Keeping eyes open.",
    "Copy. We're on it.",
    "10-4, moving out.",
    "Roger. Out.",
    "Copy, Dispatch. Be advised traffic is heavy.",
    "Understood. Proceeding.",
    "Copy that, standing by.",
    "10-4. Will advise when on scene.",
    "Roger. Over.",
    "Copy, switching channels.",
    "10-4, taking the long way around Sector 4.",
    "Understood, Dispatch. Stay frosty.",
    "10-4. Do we have any riot gear left in the armory?",
    "Acknowledged. My hover-cruiser is making that weird noise again.",
    "Roger. I'm pretty sure someone just tried to hack my steering wheel.",
    "Solid copy. Wait, are we still under martial law?",
    "Solid copy. My partner is asleep, I'm handling this alone.",
    "Loud and clear. I'm not doing any more paperwork today, just saying.",
    "Solid copy. Does anyone else smell burning plastic?",
    "10-4. I dropped my gun in a puddle of bio-sludge.",
    "Understood. Just don't send me back to the Gamma Slums.",
    "Roger. I'm not doing any more paperwork today, just saying.",
    "Understood. Wait, are we still under martial law?",
    "10-4. I think my cruiser just became sentient. It's judging my driving.",
    "Copy that. My cruiser's AC is blowing out neon smoke.",
    "Copy that. I just hit a pothole the size of a crater.",
    "Roger. I think my comms are tapped by a corporate spy.",
    "Copy that. If this is another false alarm, I'm quitting.",
    "Roger. I dropped my gun in a puddle of bio-sludge.",
    "Understood. Please tell me this isn't another glitching android.",
    "Acknowledged. Are you sure? The GPS says that address doesn't exist anymore.",
    "Understood. Can you send the cleanup crew in advance?",
    "10-4. I'm going to need a bigger gun for this sector.",
    "Solid copy. I swear my radio is picking up ancient pop music.",
    "10-4. Can we get some air support on this?",
    "Acknowledged. I'm ignoring that last transmission, it sounded like a prank.",
    "Loud and clear. My partner just threw up. We might be delayed.",
    "Copy that. I think I'm hallucinating. Or the billboards are talking to me.",
    "Understood. I think my neural link is lagging.",
    "Understood. Did you hear that? Sounded like an explosion in Sector 7.",
    "Acknowledged. I'm going to need backup, and probably a mop.",
    "Roger. Tell the Chief I need a raise.",
    "Solid copy. I need a coffee break after this one.",
    "Understood. Are we getting hazard pay for this?",
    "Solid copy. I'm going to need a bigger gun for this sector.",
    "Acknowledged. My partner is asleep, I'm handling this alone.",
    "Solid copy. My dashcam is broken again, just so you know.",
    "Understood. My partner is asleep, I'm handling this alone.",
    "Solid copy. I'm pretty sure someone just tried to hack my steering wheel.",
    "Solid copy. Just passed a guy walking a robotic alligator.",
    "10-4. My hover-cruiser is making that weird noise again.",
    "Solid copy. Are you sure? The GPS says that address doesn't exist anymore.",
    "Understood. My stun baton is out of charge. I'll have to use harsh language.",
    "Understood. I'm ignoring that last transmission, it sounded like a prank.",
    "Roger. Can you repeat? A hover-train just went over my head.",
    "Copy that. My partner just threw up. We might be delayed.",
    "Acknowledged. I need a coffee break after this one.",
    "Solid copy. Please tell me this isn't another glitching android.",
    "Loud and clear. Are we getting hazard pay for this?",
    "Roger. I think my cruiser just became sentient. It's judging my driving.",
    "Copy that. I just saw a rat the size of a dog. I'm staying in the car.",
    "10-4. I'm currently stuck behind a garbage drone, give me a minute.",
    "Acknowledged. My stun baton is out of charge. I'll have to use harsh language.",
    "Loud and clear. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Solid copy. I'm not getting paid enough for this.",
    "Solid copy. My body armor is beeping, I think the battery is low.",
    "Roger. I think I'm hallucinating. Or the billboards are talking to me.",
    "Roger. Just passed a guy walking a robotic alligator.",
    "10-4. I think my comms are tapped by a corporate spy.",
    "Copy that. Did anyone else see that flash in the sky?",
    "Acknowledged. I think I'm hallucinating. Or the billboards are talking to me.",
    "Solid copy. Do we have any riot gear left in the armory?",
    "Acknowledged. My dashcam is broken again, just so you know.",
    "Loud and clear. My stun baton is out of charge. I'll have to use harsh language.",
    "Loud and clear. I just saw a rat the size of a dog. I'm staying in the car.",
    "10-4. I just spilled synth-caf all over my console.",
    "Acknowledged. Let's hope they don't have laser weapons this time.",
    "Loud and clear. Just passed a guy walking a robotic alligator.",
    "Acknowledged. Can you repeat? A hover-train just went over my head.",
    "Understood. Can we authorize lethal force just in case?",
    "Understood. My hover-cruiser is making that weird noise again.",
    "Copy that. I'm going to need backup, and probably a mop.",
    "Acknowledged. If this is another false alarm, I'm quitting.",
    "Solid copy. Did you hear that? Sounded like an explosion in Sector 7.",
    "Acknowledged. My partner just threw up. We might be delayed.",
    "10-4. Does anyone else smell burning plastic?",
    "Copy that. Can we get some air support on this?",
    "Solid copy. I just spilled synth-caf all over my console.",
    "Understood. I'm not getting paid enough for this.",
    "Roger. I think my neural link is lagging.",
    "Copy that. I'm not going in there without a hazmat suit.",
    "Copy that. I just spilled synth-caf all over my console.",
    "Copy that. Just passed a guy walking a robotic alligator.",
    "Loud and clear. Are you sure? The GPS says that address doesn't exist anymore.",
    "Roger. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Solid copy. I'm ignoring that last transmission, it sounded like a prank.",
    "Solid copy. My partner just threw up. We might be delayed.",
    "Understood. My cruiser's AC is blowing out neon smoke.",
    "Loud and clear. Do we have any riot gear left in the armory?",
    "Copy that. Wait, are we still under martial law?",
    "Copy that. My hover-cruiser is making that weird noise again.",
    "Loud and clear. I dropped my gun in a puddle of bio-sludge.",
    "Loud and clear. I'm going to need backup, and probably a mop.",
    "Copy that. Is it too late to request a desk job?",
    "Loud and clear. I'm taking my lunch break right after this.",
    "Copy that. Tell the Chief I need a raise.",
    "Solid copy. I just saw a rat the size of a dog. I'm staying in the car.",
    "Acknowledged. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Solid copy. Who designed these uniforms? They chafe.",
    "Loud and clear. Who designed these uniforms? They chafe.",
    "10-4. Who designed these uniforms? They chafe.",
    "Loud and clear. I just spilled synth-caf all over my console.",
    "Acknowledged. I just hit a pothole the size of a crater.",
    "Solid copy. My hover-cruiser is making that weird noise again.",
    "Understood. I think my comms are tapped by a corporate spy.",
    "10-4. I'm going to need backup, and probably a mop.",
    "Roger. Do we have any riot gear left in the armory?",
    "Acknowledged. I'm not getting paid enough for this.",
    "Loud and clear. I think I'm hallucinating. Or the billboards are talking to me.",
    "Understood. I think I'm hallucinating. Or the billboards are talking to me.",
    "Roger. Can you send the cleanup crew in advance?",
    "Loud and clear. I'm ignoring that last transmission, it sounded like a prank.",
    "Understood. Tell the Chief I need a raise.",
    "Loud and clear. Does anyone else smell burning plastic?",
    "Loud and clear. I need a coffee break after this one.",
    "Acknowledged. My cruiser's AC is blowing out neon smoke.",
    "Solid copy. My siren is jammed on the 'screaming banshee' setting.",
    "Acknowledged. My body armor is beeping, I think the battery is low.",
    "Understood. Does anyone else smell burning plastic?",
    "Loud and clear. Tell the Chief I need a raise.",
    "Understood. Who designed these uniforms? They chafe.",
    "Understood. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Solid copy. I'm going to need backup, and probably a mop.",
    "Copy that. My dashcam is broken again, just so you know.",
    "10-4. Wait, are we still under martial law?",
    "Solid copy. I just hit a pothole the size of a crater.",
    "Solid copy. I think my comms are tapped by a corporate spy.",
    "Acknowledged. Are we getting hazard pay for this?",
    "Understood. I'm not doing any more paperwork today, just saying.",
    "Loud and clear. Can we get some air support on this?",
    "Roger. Are you sure? The GPS says that address doesn't exist anymore.",
    "Acknowledged. Just passed a guy walking a robotic alligator.",
    "Acknowledged. I dropped my gun in a puddle of bio-sludge.",
    "10-4. I'm taking my lunch break right after this.",
    "Acknowledged. I think my cruiser just became sentient. It's judging my driving.",
    "Solid copy. Did anyone else see that flash in the sky?",
    "10-4. I just hit a pothole the size of a crater.",
    "Roger. Can we authorize lethal force just in case?",
    "Roger. I'm rerouting, the main bridge is currently on fire.",
    "10-4. I'm ignoring that last transmission, it sounded like a prank.",
    "Copy that. I think my cruiser just became sentient. It's judging my driving.",
    "Roger. Wait, are we still under martial law?",
    "10-4. I'm out of synthetic donuts, can someone bring me some?",
    "Acknowledged. I'm out of synthetic donuts, can someone bring me some?",
    "Understood. Are you sure? The GPS says that address doesn't exist anymore.",
    "Roger. I'm going to need backup, and probably a mop.",
    "10-4. I just saw a rat the size of a dog. I'm staying in the car.",
    "Copy that. My stun baton is out of charge. I'll have to use harsh language.",
    "Understood. Is it too late to request a desk job?",
    "Roger. Just don't send me back to the Gamma Slums.",
    "Solid copy. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "10-4. Is it too late to request a desk job?",
    "Copy that. My siren is jammed on the 'screaming banshee' setting.",
    "Loud and clear. My hover-cruiser is making that weird noise again.",
    "Solid copy. I'm currently stuck behind a garbage drone, give me a minute.",
    "Solid copy. I think I'm hallucinating. Or the billboards are talking to me.",
    "Loud and clear. I think my cruiser just became sentient. It's judging my driving.",
    "Acknowledged. I'm not going in there without a hazmat suit.",
    "Roger. I'm not going in there without a hazmat suit.",
    "Acknowledged. I think my comms are tapped by a corporate spy.",
    "Acknowledged. I think my neural link is lagging.",
    "Solid copy. I'm not doing any more paperwork today, just saying.",
    "Acknowledged. Please tell me this isn't another glitching android.",
    "Solid copy. I dropped my gun in a puddle of bio-sludge.",
    "Loud and clear. Just don't send me back to the Gamma Slums.",
    "Roger. My partner just threw up. We might be delayed.",
    "Understood. My dashcam is broken again, just so you know.",
    "Loud and clear. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Roger. Are we getting hazard pay for this?",
    "Understood. Can we get some air support on this?",
    "Roger. I'm not getting paid enough for this.",
    "Loud and clear. I'm pretty sure someone just tried to hack my steering wheel.",
    "Copy that. Can we authorize lethal force just in case?",
    "Loud and clear. I think my neural link is lagging.",
    "10-4. I'm not going in there without a hazmat suit.",
    "Roger. If this is another false alarm, I'm quitting.",
    "Roger. I'm ignoring that last transmission, it sounded like a prank.",
    "Acknowledged. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Roger. I'm taking my lunch break right after this.",
    "Solid copy. If this is another false alarm, I'm quitting.",
    "Understood. I need a coffee break after this one.",
    "Copy that. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "10-4. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Roger. My stun baton is out of charge. I'll have to use harsh language.",
    "10-4. My dashcam is broken again, just so you know.",
    "Acknowledged. Do we have any riot gear left in the armory?",
    "Understood. I think my cruiser just became sentient. It's judging my driving.",
    "10-4. Can you repeat? A hover-train just went over my head.",
    "Understood. I'm taking my lunch break right after this.",
    "Copy that. I'm out of synthetic donuts, can someone bring me some?",
    "Solid copy. Just don't send me back to the Gamma Slums.",
    "Roger. My hover-cruiser is making that weird noise again.",
    "Loud and clear. I'm going to need a bigger gun for this sector.",
    "Understood. I'm currently stuck behind a garbage drone, give me a minute.",
    "Copy that. My partner is asleep, I'm handling this alone.",
    "Solid copy. I'm taking my lunch break right after this.",
    "Understood. I'm going to need a bigger gun for this sector.",
    "Acknowledged. Wait, are we still under martial law?",
    "Loud and clear. I think my comms are tapped by a corporate spy.",
    "Loud and clear. I'm rerouting, the main bridge is currently on fire.",
    "Understood. If this is another false alarm, I'm quitting.",
    "10-4. If this is another false alarm, I'm quitting.",
    "10-4. I'm not getting paid enough for this.",
    "Copy that. Let's hope they don't have laser weapons this time.",
    "Acknowledged. Can you send the cleanup crew in advance?",
    "Copy that. I need a coffee break after this one.",
    "10-4. My partner just threw up. We might be delayed.",
    "Understood. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Understood. My body armor is beeping, I think the battery is low.",
    "Copy that. I'm currently stuck behind a garbage drone, give me a minute.",
    "Copy that. I'm not doing any more paperwork today, just saying.",
    "Roger. My body armor is beeping, I think the battery is low.",
    "Roger. I'm currently stuck behind a garbage drone, give me a minute.",
    "Solid copy. My stun baton is out of charge. I'll have to use harsh language.",
    "Understood. My siren is jammed on the 'screaming banshee' setting.",
    "Loud and clear. Can we authorize lethal force just in case?",
    "Solid copy. My cruiser's AC is blowing out neon smoke.",
    "10-4. I'm pretty sure someone just tried to hack my steering wheel.",
    "Loud and clear. Did you hear that? Sounded like an explosion in Sector 7.",
    "10-4. Can you send the cleanup crew in advance?",
    "Acknowledged. I'm rerouting, the main bridge is currently on fire.",
    "Solid copy. Let's hope they don't have laser weapons this time.",
    "Solid copy. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "10-4. Did you hear that? Sounded like an explosion in Sector 7.",
    "Solid copy. I'm not going in there without a hazmat suit.",
    "Solid copy. I think my cruiser just became sentient. It's judging my driving.",
    "Copy that. Does anyone else smell burning plastic?",
    "Loud and clear. My cruiser's AC is blowing out neon smoke.",
    "Copy that. Did you hear that? Sounded like an explosion in Sector 7.",
    "Understood. I'm pretty sure someone just tried to hack my steering wheel.",
    "Acknowledged. I just spilled synth-caf all over my console.",
    "Copy that. Are you sure? The GPS says that address doesn't exist anymore.",
    "Loud and clear. I'm not getting paid enough for this.",
    "Acknowledged. I'm taking my lunch break right after this.",
    "Roger. I just saw a rat the size of a dog. I'm staying in the car.",
    "Understood. My partner just threw up. We might be delayed.",
    "10-4. My body armor is beeping, I think the battery is low.",
    "Acknowledged. Can we authorize lethal force just in case?",
    "10-4. My partner is asleep, I'm handling this alone.",
    "Solid copy. Can you repeat? A hover-train just went over my head.",
    "10-4. Tell the Chief I need a raise.",
    "Copy that. Can you repeat? A hover-train just went over my head.",
    "Copy that. I'm taking my lunch break right after this.",
    "Loud and clear. Can you send the cleanup crew in advance?",
    "Acknowledged. Tell the Chief I need a raise.",
    "Copy that. I dropped my gun in a puddle of bio-sludge.",
    "10-4. Please tell me this isn't another glitching android.",
    "10-4. Can we authorize lethal force just in case?",
    "Roger. I'm pretty sure I'm being followed by a swarm of advertising drones.",
    "Loud and clear. Did anyone else see that flash in the sky?",
    "Acknowledged. I'm not doing any more paperwork today, just saying.",
    "Roger. I'm out of synthetic donuts, can someone bring me some?",
    "Loud and clear. Let's hope they don't have laser weapons this time.",
    "10-4. I swear my radio is picking up ancient pop music.",
    "Acknowledged. My siren is jammed on the 'screaming banshee' setting.",
    "Acknowledged. Can we get some air support on this?",
    "10-4. Are we getting hazard pay for this?",
    "Understood. I'm rerouting, the main bridge is currently on fire.",
    "Copy that. Are we getting hazard pay for this?",
    "Roger. My dashcam is broken again, just so you know.",
    "Copy that. I'm rerouting, the main bridge is currently on fire.",
    "Acknowledged. Does anyone else smell burning plastic?",
    "Roger. Who designed these uniforms? They chafe.",
    "Acknowledged. Just don't send me back to the Gamma Slums.",
    "10-4. I think I'm hallucinating. Or the billboards are talking to me.",
    "Roger. Did you hear that? Sounded like an explosion in Sector 7.",
    "Understood. I'm not going in there without a hazmat suit.",
    "Loud and clear. I just hit a pothole the size of a crater.",
    "Loud and clear. I'm currently stuck behind a garbage drone, give me a minute.",
    "Roger. I'm going to need a bigger gun for this sector.",
    "Roger. I need a coffee break after this one.",
    "Copy that. Do we have any riot gear left in the armory?",
    "Roger. Is it too late to request a desk job?",
    "Copy that. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Loud and clear. My body armor is beeping, I think the battery is low.",
    "Loud and clear. If this is another false alarm, I'm quitting.",
    "Roger. I just spilled synth-caf all over my console.",
    "Understood. I swear my radio is picking up ancient pop music.",
    "Understood. Can you repeat? A hover-train just went over my head.",
    "Copy that. Please tell me this isn't another glitching android.",
    "Copy that. I'm ignoring that last transmission, it sounded like a prank.",
    "Roger. Please tell me this isn't another glitching android.",
    "Understood. Do we have any riot gear left in the armory?",
    "Understood. I just hit a pothole the size of a crater.",
    "10-4. I need a coffee break after this one.",
    "Copy that. I'm not getting paid enough for this.",
    "Loud and clear. Can you repeat? A hover-train just went over my head.",
    "Solid copy. Is it too late to request a desk job?",
    "Solid copy. Can we get some air support on this?",
    "Roger. My partner is asleep, I'm handling this alone.",
    "Roger. My cruiser's AC is blowing out neon smoke.",
    "Acknowledged. I swear my radio is picking up ancient pop music.",
    "Roger. Did anyone else see that flash in the sky?",
    "Solid copy. Are we getting hazard pay for this?",
    "Loud and clear. I'm not going in there without a hazmat suit.",
    "Roger. My siren is jammed on the 'screaming banshee' setting.",
    "10-4. My siren is jammed on the 'screaming banshee' setting.",
    "Understood. I just spilled synth-caf all over my console.",
    "10-4. Did anyone else see that flash in the sky?",
    "Understood. I just saw a rat the size of a dog. I'm staying in the car.",
    "10-4. My cruiser is out of windshield washer fluid, and the rain is acidic.",
    "Acknowledged. I just saw a rat the size of a dog. I'm staying in the car.",
    "Solid copy. I think my neural link is lagging.",
    "Acknowledged. I'm going to need a bigger gun for this sector.",
    "Acknowledged. Is it too late to request a desk job?",
    "Roger. Can we get some air support on this?",
    "Solid copy. Tell the Chief I need a raise.",
    "10-4. I'm not doing any more paperwork today, just saying.",
    "Copy that. Can you send the cleanup crew in advance?",
    "Copy that. My body armor is beeping, I think the battery is low.",
    "Understood. I'm out of synthetic donuts, can someone bring me some?",
    "Copy that. Who designed these uniforms? They chafe.",
    "Loud and clear. I'm out of synthetic donuts, can someone bring me some?",
    "Copy that. I swear my radio is picking up ancient pop music.",
    "10-4. I'm rerouting, the main bridge is currently on fire.",
    "Loud and clear. My dashcam is broken again, just so you know.",
    "Understood. Just passed a guy walking a robotic alligator.",
    "10-4. Just passed a guy walking a robotic alligator."
,
    "Roger. I'm pulling over a flying garbage truck.",
    "Solid copy. Does anyone have a spare USB-C cable for my taser?",
    "Solid copy. I need backup, I'm surrounded by angry hipsters.",
    "Solid copy. I just found a perfectly preserved hamburger.",
    "Roger. I just found a stash of pre-war comic books.",
    "Solid copy. I'm stuck in a holographic maze.",
    "Understood. I need a new partner, this one keeps glitching out.",
    "Copy, Dispatch. My siren is making a weird dubstep noise.",
    "Copy that. I'm confiscating a crate of illegal cyber-pets.",
    "Roger. I'm out of ammo and patience.",
    "Solid copy. The suspect is a genetically modified gorilla.",
    "Loud and clear. Can I get a drone strike on this location? Just kidding.",
    "Loud and clear. I'm putting in my two weeks notice after this shift.",
    "Loud and clear. I need a new badge, mine melted.",
    "Copy, Dispatch. I just had to arrest a holographic billboard.",
    "Loud and clear. My badge is out of battery.",
    "Loud and clear. The air quality index just hit 'apocalyptic'.",
    "Copy that. I just found a stash of pre-war comic books.",
    "Acknowledged. I'm not going to Sector 4 without a SWAT team.",
    "Solid copy. I just got my firewall hacked by a smart-fridge.",
    "10-4. I'm watching a cyber-duel in the middle of the street.",
    "Loud and clear. I'm not going to Sector 4 without a SWAT team.",
    "Copy that. I just had to arrest a holographic billboard.",
    "Acknowledged. I'm confiscating a crate of illegal cyber-implants.",
    "Copy, Dispatch. Can you send animal control? We have a feral cyber-mastiff here.",
    "Copy, Dispatch. Can I get a drone strike on this location? Just kidding.",
    "Copy, Dispatch. I need backup, I'm facing a swarm of murder-hornets.",
    "Solid copy. I just found a briefcase full of pure, uncut data.",
    "Copy, Dispatch. I'm putting in my two weeks notice after this shift.",
    "Copy, Dispatch. I'm stuck in traffic behind a hover-tank.",
    "Roger. My siren is making a weird dubstep noise.",
    "Loud and clear. My boots are melting into the pavement.",
    "Copy that. I'm getting interference from a pirate radio station.",
    "Loud and clear. I just got mugged by a group of orphans.",
    "Roger. My cruiser's paint job is peeling from the smog.",
    "Understood. I need a tow truck, my anti-grav thrusters just died.",
    "10-4. My cyber-arm is stuck in a salute.",
    "Roger. Are we getting paid hazard overtime for this?",
    "Copy that. I'm going off the grid for a 10-minute nap.",
    "Solid copy. Just chased a suspect into a virtual reality den.",
    "Copy that. My badge is out of battery.",
    "Copy, Dispatch. My badge is out of battery.",
    "Loud and clear. I'm watching a cyber-duel in the middle of the street.",
    "Copy that. I just got mugged by a group of orphans.",
    "Loud and clear. I'm out of ammo and patience.",
    "Copy, Dispatch. I need a new partner, this one keeps glitching out.",
    "Loud and clear. I need backup, I'm facing a swarm of murder-hornets.",
    "Acknowledged. I just stepped in a puddle of unidentified glowing goo.",
    "Copy, Dispatch. I need a new badge, mine melted.",
    "Roger. I'm putting in my two weeks notice after this shift.",
    "Solid copy. My siren is making a weird dubstep noise.",
    "Solid copy. Someone stole my hover-car's anti-grav emitters at a red light.",
    "Solid copy. I need a medic, my cyber-arm is sparking.",
    "Copy, Dispatch. I'm confiscating a crate of illegal cyber-pets.",
    "Copy, Dispatch. Just ran over a rogue Roomba.",
    "Roger. Someone is throwing cyber-bricks from the overpass.",
    "Solid copy. I'm arresting a guy for stealing wifi.",
    "Acknowledged. I'm getting interference from a pirate radio station.",
    "Roger. My cruiser's radio only plays heavy metal.",
    "Understood. My partner keeps talking to his gun.",
    "Understood. I need to file a grievance against the cyber-mayor.",
    "10-4. I need to file a grievance against the cyber-mayor.",
    "Roger. There is a man eating a synthetic tire on the corner of 5th and Main.",
    "Copy that. It is raining literal acid right now.",
    "Loud and clear. The neon lights are giving me a severe migraine.",
    "Understood. I need a medic, my cyber-arm is sparking.",
    "10-4. I just got a tip about a secret cyber-cult.",
    "Copy, Dispatch. I'm negotiating with a hostage-taking vending machine.",
    "Copy, Dispatch. Someone spray-painted anti-corp slogans on my windshield.",
    "Loud and clear. Just saw a guy jump over a 3-story building.",
    "Roger. I just found a briefcase full of pure, uncut data.",
    "Roger. The suspect is a genetically modified gorilla.",
    "10-4. My uniform is covered in neon paint.",
    "Loud and clear. Just chased a suspect into a virtual reality den.",
    "10-4. I'm pulling over a flying garbage truck.",
    "Copy that. I need backup, I'm surrounded by angry hipsters.",
    "Acknowledged. My uniform is covered in neon paint.",
    "Solid copy. My cruiser's radio only plays heavy metal.",
    "10-4. I'm stuck in a holographic maze.",
    "Understood. My cruiser smells like burnt circuitry and ozone.",
    "10-4. The suspect is wearing a hat made of tin foil.",
    "Acknowledged. I'm trapped in an elevator with a malfunctioning AI.",
    "Roger. I just got my firewall hacked by a smart-fridge.",
    "Acknowledged. My cruiser's radio only plays heavy metal.",
    "Loud and clear. I'm confiscating a crate of illegal cyber-pets.",
    "Understood. Are we getting paid hazard overtime for this?",
    "Loud and clear. My cruiser's AI is having an existential crisis.",
    "Solid copy. My cruiser's paint job is peeling from the smog.",
    "Copy that. I think my partner might actually be a synth.",
    "Understood. I need backup, there are too many feral drones here.",
    "10-4. I need backup, there are too many feral drones here.",
    "Loud and clear. I'm confiscating a crate of illegal organic vegetables.",
    "Copy that. My neural link is lagging, can you repeat?",
    "Copy, Dispatch. Are we getting paid hazard overtime for this?",
    "Copy, Dispatch. I'm pulling over a guy on a rocket-powered skateboard.",
    "Roger. I just accidentally shot a civilian drone.",
    "Roger. I'm going off the grid for a 10-minute nap.",
    "Roger. The suspect just uploaded his consciousness to the net.",
    "10-4. I just stepped in a puddle of unidentified glowing goo.",
    "Roger. The suspect is wearing a hat made of tin foil.",
    "Copy that. I just found a perfectly preserved hamburger.",
    "Copy that. I just got a speeding ticket from a traffic camera while on duty.",
    "Loud and clear. The sky is literally purple right now.",
    "Roger. I'm watching a building sink into the ground.",
    "10-4. Can someone pick me up a synth-burger from the drive-thru?",
    "Understood. Can someone pick me up a synth-burger from the drive-thru?",
    "Loud and clear. I'm stuck in a VR loop, send help.",
    "10-4. My neural link is lagging, can you repeat?",
    "Copy, Dispatch. I'm watching a gang war over a patch of grass.",
    "Acknowledged. My cruiser's paint job is peeling from the smog.",
    "Loud and clear. The suspect just uploaded his consciousness to the net.",
    "Copy, Dispatch. The air quality index just hit 'apocalyptic'.",
    "Roger. I need a new badge, mine melted.",
    "Acknowledged. I just found a hidden underground city.",
    "Loud and clear. My cruiser's AI is refusing to open the doors.",
    "Roger. Can I get a drone strike on this location? Just kidding.",
    "Solid copy. My uniform is covered in neon paint.",
    "Solid copy. My cruiser smells like burnt circuitry and ozone.",
    "Copy that. I'm arresting a guy for trying to fly.",
    "Acknowledged. I think my cybernetics need an oil change.",
    "Understood. I'm stuck in a holographic maze.",
    "10-4. I'm confiscating a crate of illegal organic vegetables.",
    "Copy, Dispatch. Can someone pick me up a synth-burger from the drive-thru?",
    "10-4. My visor HUD is stuck displaying ads for soy-paste.",
    "Copy that. I need a tow truck, my anti-grav thrusters just died.",
    "Solid copy. I'm confiscating a crate of illegal cyber-pets.",
    "Copy that. The suspect is wearing a hat made of tin foil.",
    "Solid copy. I'm arresting a guy for walking too fast.",
    "10-4. My partner keeps talking to his gun.",
    "Copy that. The sky is literally purple right now.",
    "Understood. Tell the Chief I need a vacation to Mars.",
    "Understood. My boots are melting into the pavement.",
    "Acknowledged. I just got my firewall hacked by a smart-fridge.",
    "Copy, Dispatch. I'm not going to Sector 4 without a SWAT team.",
    "10-4. I'm arresting a guy for trying to fly.",
    "Solid copy. The suspect is wearing a suit made of mirrors.",
    "Roger. I think someone spiked my water bottle with nanites.",
    "Acknowledged. The air quality index just hit 'apocalyptic'.",
    "Loud and clear. Tell the Chief I need a vacation to Mars.",
    "Copy that. I need to file a grievance against the cyber-mayor.",
    "Roger. I need a coffee IV drip right now.",
    "Solid copy. The neon lights are giving me a severe migraine.",
    "Acknowledged. The suspect is a genetically modified gorilla.",
    "Loud and clear. My gun jammed, sending a hard reboot signal to it now.",
    "Loud and clear. The suspect is armed with a sonic cannon.",
    "Solid copy. The suspect is armed with a sonic cannon.",
    "Copy, Dispatch. My taser just exploded.",
    "Copy that. There is a man eating a synthetic tire on the corner of 5th and Main.",
    "10-4. I just got mugged by a group of orphans.",
    "10-4. My taser just exploded.",
    "Loud and clear. I'm trapped in an elevator with a malfunctioning AI.",
    "Copy, Dispatch. I just found a stash of pre-war comic books.",
    "Understood. I'm arresting a mime for disturbing the peace.",
    "Loud and clear. Can you order me a pizza? I haven't eaten in 12 hours.",
    "Copy, Dispatch. My uniform is covered in neon paint.",
    "Roger. I'm arresting a mime for disturbing the peace.",
    "Loud and clear. Someone spray-painted anti-corp slogans on my windshield.",
    "Copy, Dispatch. I need backup, I'm surrounded by angry hipsters.",
    "10-4. I need a tech-priest to bless my gun.",
    "Copy, Dispatch. I just got mugged by a group of orphans.",
    "Copy, Dispatch. I'm confiscating a crate of illegal cyber-implants.",
    "Solid copy. I'm negotiating with a hostage-taking vending machine.",
    "Loud and clear. I just got a speeding ticket from a traffic camera while on duty.",
    "Copy that. My cyber-arm is stuck in a salute.",
    "Copy that. I'm watching a cyber-duel in the middle of the street.",
    "Roger. I need backup, there are too many feral drones here.",
    "Loud and clear. The suspect just phased through a solid wall.",
    "Loud and clear. My cyber-eye is acting up again.",
    "Acknowledged. I just got a speeding ticket from a traffic camera while on duty.",
    "10-4. I think my cybernetics need an oil change.",
    "Copy that. I need a coffee IV drip right now.",
    "Acknowledged. I need a tow truck, my anti-grav thrusters just died.",
    "Loud and clear. I'm watching a gang war over a patch of grass.",
    "10-4. Someone spray-painted anti-corp slogans on my windshield.",
    "Understood. I'm negotiating with a hostage-taking vending machine.",
    "Solid copy. I'm stuck in traffic behind a hover-tank.",
    "Copy, Dispatch. It is raining literal acid right now.",
    "Copy, Dispatch. My cruiser's paint job is peeling from the smog.",
    "Roger. My partner keeps talking to his gun.",
    "Solid copy. I need a tow truck, my anti-grav thrusters just died.",
    "Solid copy. The air quality index just hit 'apocalyptic'.",
    "Loud and clear. I just got a tip about a secret cyber-cult.",
    "Understood. I think my cybernetics need an oil change.",
    "Copy, Dispatch. My gun jammed, sending a hard reboot signal to it now.",
    "Understood. I'm confiscating a crate of illegal cyber-implants.",
    "Loud and clear. My neural link is lagging, can you repeat?",
    "Copy, Dispatch. I just confiscated a plasma rifle from a toddler.",
    "10-4. The suspect just uploaded his consciousness to the net.",
    "Understood. The air quality index just hit 'apocalyptic'.",
    "Understood. The neon lights are giving me a severe migraine.",
    "Copy that. I'm watching a guy try to hack a fire hydrant.",
    "Copy, Dispatch. Does anyone have a spare USB-C cable for my taser?",
    "Copy that. I'm watching a hover-car race on the freeway.",
    "10-4. I'm not going to Sector 4 without a SWAT team.",
    "Roger. I'm hiding in an alley until the rioters pass.",
    "Copy that. Can someone reboot the precinct's main router? I lost connection.",
    "Loud and clear. Does anyone have a spare USB-C cable for my taser?",
    "Loud and clear. I'm pretty sure my synth-coffee is sentient.",
    "Copy, Dispatch. The suspect just uploaded his consciousness to the net.",
    "Loud and clear. I just had to arrest a holographic billboard.",
    "Copy, Dispatch. I just got my firewall hacked by a smart-fridge.",
    "Understood. I'm confiscating a crate of illegal cyber-pets.",
    "Loud and clear. I'm confiscating a crate of illegal cyber-implants.",
    "Solid copy. My cruiser's AI is refusing to open the doors.",
    "Solid copy. Just ran over a rogue Roomba.",
    "Loud and clear. My cruiser's paint job is peeling from the smog.",
    "Loud and clear. I just got propositioned by a joy-toy.",
    "10-4. Are we getting paid hazard overtime for this?",
    "10-4. I'm watching a hover-car race on the freeway.",
    "10-4. My boots are melting into the pavement.",
    "10-4. I just had to arrest a holographic billboard.",
    "Copy that. My taser just exploded.",
    "Copy that. I'm arresting a guy for walking too fast.",
    "Copy, Dispatch. I'm watching a hover-car race on the freeway.",
    "Copy, Dispatch. My cruiser smells like burnt circuitry and ozone.",
    "Copy, Dispatch. I'm pulling over a flying garbage truck.",
    "10-4. I'm pulling over a guy on a rocket-powered skateboard.",
    "10-4. Can you order me a pizza? I haven't eaten in 12 hours.",
    "Solid copy. My cruiser's AI is having an existential crisis.",
    "Copy, Dispatch. Can someone reboot the precinct's main router? I lost connection.",
    "10-4. I'm hiding in an alley until the rioters pass.",
    "Loud and clear. It is raining literal acid right now.",
    "Copy that. I'm trapped in an elevator with a malfunctioning AI.",
    "Solid copy. I need to file a grievance against the cyber-mayor.",
    "Understood. I just got a tip about a secret cyber-cult.",
    "Acknowledged. The suspect just uploaded his consciousness to the net.",
    "Solid copy. Just saw a guy jump over a 3-story building.",
    "Acknowledged. I need backup, I'm facing a swarm of murder-hornets.",
    "Acknowledged. I need a medic, my cyber-arm is sparking.",
    "Solid copy. There is a man eating a synthetic tire on the corner of 5th and Main.",
    "Copy, Dispatch. I'm confiscating a crate of illegal organic vegetables.",
    "10-4. I need a medic, my cyber-arm is sparking.",
    "Loud and clear. I think someone spiked my water bottle with nanites.",
    "Understood. I just saw a rat the size of a hover-bike.",
    "Solid copy. My badge is out of battery.",
    "Copy that. I just stepped in a puddle of unidentified glowing goo.",
    "Copy that. The suspect just uploaded his consciousness to the net.",
    "Acknowledged. I'm negotiating with a hostage-taking vending machine.",
    "10-4. I just accidentally shot a civilian drone.",
    "Understood. I'm stuck in traffic behind a hover-tank.",
    "Roger. I just stepped in a puddle of unidentified glowing goo.",
    "Understood. I just found a stash of pre-war comic books.",
    "Understood. My uniform is covered in neon paint.",
    "Copy that. Someone stole my hover-car's anti-grav emitters at a red light.",
    "Solid copy. I need a new badge, mine melted.",
    "Solid copy. I'm watching a cyber-duel in the middle of the street.",
    "Acknowledged. Someone spray-painted anti-corp slogans on my windshield.",
    "Solid copy. I'm watching a building sink into the ground.",
    "Roger. I'm arresting a guy for walking too fast.",
    "Roger. My taser just exploded.",
    "Copy that. My boots are melting into the pavement.",
    "Solid copy. I'm trapped in an elevator with a malfunctioning AI.",
    "Roger. I think my cybernetics need an oil change.",
    "Loud and clear. My uniform is covered in neon paint.",
    "Roger. Can you order me a pizza? I haven't eaten in 12 hours.",
    "Copy that. My cruiser's AI is having an existential crisis.",
    "Loud and clear. My taser just exploded.",
    "Understood. I'm pulling over a flying garbage truck.",
    "Copy that. I need a tech-priest to bless my gun.",
    "Solid copy. The suspect just phased through a solid wall.",
    "Loud and clear. I think my partner might actually be a synth.",
    "Copy, Dispatch. I'm watching a cyber-duel in the middle of the street.",
    "Solid copy. It is raining literal acid right now.",
    "Copy, Dispatch. I think someone spiked my water bottle with nanites.",
    "Understood. I just had to arrest a holographic billboard.",
    "Copy that. I'm negotiating with a hostage-taking vending machine.",
    "Understood. My cruiser's AI is having an existential crisis.",
    "Solid copy. I think my partner might actually be a synth.",
    "Acknowledged. I think I'm falling in love with my cruiser's AI.",
    "Acknowledged. I'm stuck in traffic behind a hover-tank.",
    "10-4. I need a new badge, mine melted.",
    "Roger. I need a tech-priest to bless my gun.",
    "Acknowledged. I need to file a grievance against the cyber-mayor.",
    "Roger. Just saw a guy jump over a 3-story building.",
    "10-4. My cruiser's AI is refusing to open the doors.",
    "Copy that. I'm stuck behind a convoy of automated noodle carts.",
    "Copy that. Someone is throwing cyber-bricks from the overpass.",
    "Understood. The street gang here is entirely made up of rogue roombas.",
    "Solid copy. I just accidentally shot a civilian drone.",
    "Solid copy. I need a new partner, this one keeps glitching out.",
    "Acknowledged. The suspect is wearing a suit made of mirrors.",
    "Loud and clear. There is a man eating a synthetic tire on the corner of 5th and Main.",
    "Copy, Dispatch. I'm arresting a mime for disturbing the peace.",
    "Copy, Dispatch. I'm hiding in an alley until the rioters pass.",
    "Copy that. Can you send animal control? We have a feral cyber-mastiff here.",
    "Roger. My badge is out of battery.",
    "Copy, Dispatch. My cyber-eye is acting up again.",
    "Copy, Dispatch. Can we authorize the orbital strike yet?",
    "10-4. I'm watching a building sink into the ground.",
    "Loud and clear. I'm stuck in a holographic maze.",
    "Understood. My visor HUD is stuck displaying ads for soy-paste.",
    "Roger. Someone spray-painted anti-corp slogans on my windshield.",
    "Copy, Dispatch. I'm stuck behind a convoy of automated noodle carts.",
    "Loud and clear. I'm pulling over a guy on a rocket-powered skateboard.",
    "Loud and clear. I need a medic, my cyber-arm is sparking.",
    "Copy that. I'm hiding in an alley until the rioters pass.",
    "Solid copy. I just got mugged by a group of orphans.",
    "10-4. There is a man eating a synthetic tire on the corner of 5th and Main.",
    "Copy that. I need a medic, my cyber-arm is sparking.",
    "Loud and clear. Someone stole my hover-car's anti-grav emitters at a red light.",
    "Understood. I just stepped in a puddle of unidentified glowing goo.",
    "Solid copy. I just confiscated a plasma rifle from a toddler.",
    "10-4. I just got a speeding ticket from a traffic camera while on duty.",
    "Loud and clear. I'm arresting a guy for walking too fast.",
    "Roger. I'm confiscating a crate of illegal organic vegetables.",
    "Loud and clear. I just confiscated a plasma rifle from a toddler.",
    "Copy that. Just chased a suspect into a virtual reality den.",
    "Understood. I'm out of ammo and patience.",
    "Roger. I just saw a rat the size of a hover-bike.",
    "Understood. My cruiser's radio only plays heavy metal.",
    "Solid copy. I'm getting interference from a pirate radio station.",
    "Acknowledged. There is a man eating a synthetic tire on the corner of 5th and Main.",
    "Copy that. I just found a briefcase full of pure, uncut data.",
    "Roger. Can someone pick me up a synth-burger from the drive-thru?",
    "Copy, Dispatch. The sky is literally purple right now.",
    "Understood. The suspect just phased through a solid wall.",
    "Solid copy. I'm arresting a mime for disturbing the peace.",
    "10-4. I think someone spiked my water bottle with nanites.",
    "Acknowledged. I'm putting in my two weeks notice after this shift.",
    "Acknowledged. Someone is throwing cyber-bricks from the overpass.",
    "Acknowledged. Just saw a guy jump over a 3-story building.",
    "10-4. My cruiser's AI is having an existential crisis.",
    "Solid copy. Can I get a drone strike on this location? Just kidding.",
    "Roger. I'm stuck in a holographic maze.",
    "Loud and clear. My cruiser's radio only plays heavy metal.",
    "Acknowledged. The sky is literally purple right now.",
    "Loud and clear. I'm arresting a guy for trying to fly.",
    "Copy, Dispatch. I'm watching a guy try to hack a fire hydrant.",
    "10-4. I need a new partner, this one keeps glitching out.",
    "Roger. Just ran over a rogue Roomba.",
    "Solid copy. I'm putting in my two weeks notice after this shift.",
    "Solid copy. I'm out of ammo and patience.",
    "Understood. I think my partner might actually be a synth.",
    "Roger. My visor HUD is stuck displaying ads for soy-paste.",
    "Roger. The neon lights are giving me a severe migraine.",
    "Copy, Dispatch. My cruiser's AI is having an existential crisis.",
    "10-4. I just got propositioned by a joy-toy.",
    "Solid copy. I just found a hidden underground city.",
    "Solid copy. Someone is throwing cyber-bricks from the overpass.",
    "Solid copy. Are we getting paid hazard overtime for this?",
    "Loud and clear. Can someone reboot the precinct's main router? I lost connection.",
    "Understood. The suspect is wearing a suit made of mirrors.",
    "Copy that. I just confiscated a plasma rifle from a toddler.",
    "Acknowledged. Can we authorize the orbital strike yet?",
    "Copy that. Tell the Chief I need a vacation to Mars.",
    "Understood. I'm pulling over a guy on a rocket-powered skateboard.",
    "Copy that. I'm putting in my two weeks notice after this shift.",
    "Loud and clear. I just found a briefcase full of pure, uncut data.",
    "10-4. My badge is out of battery.",
    "Understood. I'm arresting a guy for trying to fly.",
    "10-4. I'm stuck in a VR loop, send help.",
    "Roger. My uniform is covered in neon paint.",
    "Solid copy. I just got a speeding ticket from a traffic camera while on duty.",
    "10-4. I'm getting interference from a pirate radio station.",
    "Solid copy. I just stepped in a puddle of unidentified glowing goo.",
    "Loud and clear. My siren is making a weird dubstep noise.",
    "Understood. My taser just exploded.",
    "Acknowledged. Can you send animal control? We have a feral cyber-mastiff here.",
    "10-4. Can someone reboot the precinct's main router? I lost connection.",
    "Copy that. My cruiser's paint job is peeling from the smog.",
    "Roger. I just got propositioned by a joy-toy.",
    "Copy, Dispatch. My cruiser's radio only plays heavy metal.",
    "Solid copy. I'm not going to Sector 4 without a SWAT team.",
    "Solid copy. I need a coffee IV drip right now.",
    "10-4. Can we authorize the orbital strike yet?",
    "Understood. I'm watching a building sink into the ground.",
    "Roger. Tell the Chief I need a vacation to Mars.",
    "Roger. I'm trapped in an elevator with a malfunctioning AI.",
    "Loud and clear. I just saw a rat the size of a hover-bike.",
    "Solid copy. My cyber-arm is stuck in a salute.",
    "Copy, Dispatch. I just found a hidden underground city.",
    "Copy, Dispatch. I'm arresting a guy for walking too fast.",
    "Solid copy. I just got a tip about a secret cyber-cult.",
    "10-4. I'm trapped in an elevator with a malfunctioning AI.",
    "Roger. I'm watching a cyber-duel in the middle of the street.",
    "Copy that. Are we getting paid hazard overtime for this?",
    "Copy, Dispatch. I'm trapped in an elevator with a malfunctioning AI.",
    "Copy that. I just got a tip about a secret cyber-cult.",
    "Roger. I'm negotiating with a hostage-taking vending machine.",
    "Understood. Someone is throwing cyber-bricks from the overpass.",
    "Understood. I'm going off the grid for a 10-minute nap.",
    "Loud and clear. I think my cybernetics need an oil change.",
    "Understood. I just got mugged by a group of orphans.",
    "Solid copy. I think I'm falling in love with my cruiser's AI.",
    "Roger. Just chased a suspect into a virtual reality den.",
    "Copy that. I'm arresting a mime for disturbing the peace.",
    "Copy, Dispatch. I think my cybernetics need an oil change.",
    "10-4. The sky is literally purple right now.",
    "Loud and clear. I just stepped in a puddle of unidentified glowing goo.",
    "Solid copy. Can someone pick me up a synth-burger from the drive-thru?",
    "Acknowledged. I just saw a rat the size of a hover-bike.",
    "Copy that. I'm arresting a guy for stealing wifi.",
    "Roger. I'm pulling over a guy on a rocket-powered skateboard.",
    "Roger. I'm pretty sure my synth-coffee is sentient.",
    "Acknowledged. I'm arresting a guy for trying to fly.",
    "Understood. I need backup, I'm surrounded by angry hipsters.",
    "Copy, Dispatch. My cyber-arm is stuck in a salute.",
    "Roger. The suspect is wearing a suit made of mirrors.",
    "Acknowledged. I'm pulling over a guy on a rocket-powered skateboard.",
    "Copy that. The suspect is armed with a sonic cannon.",
    "Understood. I'm trapped in an elevator with a malfunctioning AI.",
    "10-4. Does anyone have a spare USB-C cable for my taser?",
    "Acknowledged. My cruiser's AI is having an existential crisis.",
    "Copy that. The neon lights are giving me a severe migraine.",
    "Understood. My gun jammed, sending a hard reboot signal to it now.",
    "10-4. I'm watching a gang war over a patch of grass.",
    "Solid copy. I just saw a rat the size of a hover-bike.",
    "Roger. I'm arresting a guy for trying to fly.",
    "Loud and clear. I need a coffee IV drip right now.",
    "Acknowledged. The suspect just phased through a solid wall.",
    "Understood. I need a coffee IV drip right now.",
    "Copy, Dispatch. I think my partner might actually be a synth.",
    "Understood. It is raining literal acid right now.",
    "Copy that. I'm confiscating a crate of illegal cyber-implants.",
    "Copy, Dispatch. Just saw a guy jump over a 3-story building.",
    "Copy, Dispatch. I'm out of ammo and patience.",
    "Copy that. Can I get a drone strike on this location? Just kidding.",
    "Acknowledged. I just found a stash of pre-war comic books.",
    "Understood. I'm watching a guy try to hack a fire hydrant.",
    "Acknowledged. My cyber-eye is acting up again.",
    "Understood. I just got my firewall hacked by a smart-fridge.",
    "Solid copy. I'm going off the grid for a 10-minute nap.",
    "Acknowledged. My badge is out of battery.",
    "Copy, Dispatch. The suspect is armed with a laser-katana.",
    "Roger. Can you send animal control? We have a feral cyber-mastiff here.",
    "Copy that. The suspect is wearing a suit made of mirrors.",
    "Roger. The air quality index just hit 'apocalyptic'.",
    "Roger. Does anyone have a spare USB-C cable for my taser?",
    "Copy, Dispatch. I just got a speeding ticket from a traffic camera while on duty.",
    "Loud and clear. I'm going off the grid for a 10-minute nap.",
    "Copy that. I need a new badge, mine melted.",
    "Acknowledged. I just confiscated a plasma rifle from a toddler.",
    "10-4. It is raining literal acid right now.",
    "Loud and clear. I just found a perfectly preserved hamburger.",
    "Understood. I just found a perfectly preserved hamburger.",
    "Copy that. I just accidentally shot a civilian drone.",
    "Copy, Dispatch. I'm getting interference from a pirate radio station.",
    "Acknowledged. My cruiser smells like burnt circuitry and ozone.",
    "10-4. Can I get a drone strike on this location? Just kidding.",
    "10-4. I just found a briefcase full of pure, uncut data.",
    "Copy that. Can we authorize the orbital strike yet?",
    "Copy that. I need backup, there are too many feral drones here.",
    "Roger. Can someone reboot the precinct's main router? I lost connection.",
    "Copy that. I'm out of ammo and patience.",
    "Copy, Dispatch. I need backup, there are too many feral drones here.",
    "Solid copy. Can you send animal control? We have a feral cyber-mastiff here.",
    "10-4. I need backup, I'm surrounded by angry hipsters.",
    "Copy that. Just ran over a rogue Roomba.",
    "Understood. Can we authorize the orbital strike yet?",
    "Loud and clear. I'm watching a building sink into the ground.",
    "Copy, Dispatch. The suspect just phased through a solid wall.",
    "Copy, Dispatch. I just stepped in a puddle of unidentified glowing goo.",
    "Copy, Dispatch. Tell the Chief I need a vacation to Mars.",
    "Loud and clear. Someone is throwing cyber-bricks from the overpass.",
    "Acknowledged. I'm pulling over a flying garbage truck.",
    "Roger. I think my partner might actually be a synth.",
    "Solid copy. My gun jammed, sending a hard reboot signal to it now.",
    "Acknowledged. I'm watching a hover-car race on the freeway.",
    "Copy that. My cruiser smells like burnt circuitry and ozone.",
    "Acknowledged. I just got mugged by a group of orphans.",
    "10-4. Just ran over a rogue Roomba.",
    "Understood. Someone spray-painted anti-corp slogans on my windshield.",
    "Loud and clear. I just got my firewall hacked by a smart-fridge.",
    "Understood. I'm not going to Sector 4 without a SWAT team.",
    "Acknowledged. My taser just exploded.",
    "Acknowledged. I think someone spiked my water bottle with nanites.",
    "Roger. I'm watching a guy try to hack a fire hydrant.",
    "Copy that. The suspect is armed with a laser-katana.",
    "Copy that. Can someone pick me up a synth-burger from the drive-thru?",
    "Copy that. I'm stuck in a VR loop, send help.",
    "Copy, Dispatch. The suspect is wearing a suit made of mirrors.",
    "Acknowledged. The neon lights are giving me a severe migraine.",
    "Roger. My gun jammed, sending a hard reboot signal to it now.",
    "Copy, Dispatch. I think I'm falling in love with my cruiser's AI.",
    "Understood. My badge is out of battery.",
    "Copy that. My visor HUD is stuck displaying ads for soy-paste.",
    "Understood. I think I'm falling in love with my cruiser's AI.",
    "Roger. The suspect is armed with a sonic cannon.",
    "Roger. I think I'm falling in love with my cruiser's AI.",
    "Solid copy. I'm watching a hover-car race on the freeway.",
    "Acknowledged. I'm watching a gang war over a patch of grass.",
    "Roger. I need a tow truck, my anti-grav thrusters just died.",
    "Understood. I just got propositioned by a joy-toy.",
    "Solid copy. I'm stuck in a VR loop, send help.",
    "10-4. I'm stuck in traffic behind a hover-tank.",
    "Understood. There is a man eating a synthetic tire on the corner of 5th and Main.",
    "10-4. The suspect is wearing a suit made of mirrors.",
    "Roger. My cyber-eye is acting up again.",
    "Acknowledged. I just accidentally shot a civilian drone.",
    "Acknowledged. I just got propositioned by a joy-toy.",
    "Solid copy. I'm watching a gang war over a patch of grass.",
    "Copy, Dispatch. My neural link is lagging, can you repeat?",
    "Roger. I need backup, I'm facing a swarm of murder-hornets.",
    "Roger. I need a new partner, this one keeps glitching out.",
    "10-4. I'm out of ammo and patience.",
    "Acknowledged. My neural link is lagging, can you repeat?",
    "10-4. The air quality index just hit 'apocalyptic'.",
    "Solid copy. I just got propositioned by a joy-toy.",
    "Roger. I'm stuck behind a convoy of automated noodle carts.",
    "Copy, Dispatch. I'm stuck in a holographic maze.",
];

window.handleDispatchChatReactions = function(text, reactionSender, senderUnit, typingDiv) {
    const lowerText = text.toLowerCase();
    const length = text.length;
    let isYelling = (text === text.toUpperCase() && text.match(/[A-Z]/));
    let isQuestion = text.trim().endsWith("?");

    let response = "";

    // 1. Tone Checks
    if (length > 150) {
        response = "Dispatch, keep it brief. We can't read a novel while driving.";
    } else if (isYelling) {
        response = "No need to shout over the radio, we hear you loud and clear.";
    } else if (isQuestion) {
        response = "I don't have an answer to that right now, Dispatch. We are a bit busy.";
    }
    
    // 2. Strict Intent Regex Checks (\\b for word boundaries)
    else if (/\\b(bored|boring)\\b/.test(lowerText)) {
        response = "If you're bored, you can come down here and do this paperwork.";
    } else if (/\\b(joke|funny)\\b/.test(lowerText)) {
        response = "Not the time for jokes, Dispatch. Focus on the comms.";
    } else if (/\\b(radio check|comms check)\\b/.test(lowerText)) {
        response = "Loud and clear, Dispatch. Signal is 5 by 5.";
    } else if (/\\b(order|orders|command)\\b/.test(lowerText)) {
        response = "We copy the orders. Proceeding as directed.";
    } else if (/\\b(thanks|thank you)\\b/.test(lowerText)) {
        response = "You're welcome, Dispatch. Just doing our jobs.";
    } else if (/\\b(hello|hi|hey)\\b/.test(lowerText)) {
        response = "Go ahead, Dispatch. We're listening.";
    } else {
        // Fallback
        response = fallbackReactions[Math.floor(Math.random() * fallbackReactions.length)];
    }

    typingDiv.querySelector('.text').innerHTML = response;

    // Multi-Officer Banter (40% chance another officer chimes in)
    if (Math.random() < 0.4 && typeof getActiveCallsigns === 'function') {
        const active = getActiveCallsigns();
        if (active.length > 1) {
            let secondSender = active[Math.floor(Math.random() * active.length)];
            while (secondSender === reactionSender && active.length > 1) {
                secondSender = active[Math.floor(Math.random() * active.length)];
            }
            
            setTimeout(() => {
                if (typeof addChatMessage === 'function') {
                    addChatMessage(secondSender, "I completely agree with that.", 'serious', false);
                }
            }, 3000 + Math.random() * 2000);
        }
    }
};
