const PROFANITY_LINES = [
    "This shift is complete bullshit. Nothing but domestic calls.",
    "I just spilled hot coffee all over my damn lap.",
    "Who the fuck left their trash in cruiser 42?",
    "I'm so sick of this shit.",
    "If I have to deal with one more entitled civilian, I'm gonna lose my fucking mind.",
    "Where the hell is my backup?",
    "This suspect is being a complete asshole.",
    "My radar gun is completely fucked.",
    "I don't give a shit what the Sergeant says, I'm taking my break.",
    "These new regulations are total bullshit.",
    "Why the fuck is traffic so bad in Sector 4?",
    "I'm tired of dealing with these piece of shit gangers.",
    "Can someone tell this asshole to move his car?",
    "My radio is acting up again. Piece of shit tech.",
    "I'm freezing my ass off out here.",
    "Who the hell designed these uncomfortable uniforms?",
    "I've been working my ass off for no overtime pay.",
    "That suspect ran like a little bitch.",
    "I just stepped in some unidentified sludge. Fuck my life.",
    "This city is going to hell.",
    "I don't get paid enough for this shit.",
    "What the fuck was that explosion?",
    "I'm so damn tired.",
    "If I see that bastard again, I'm locking him up.",
    "This precinct is a goddamn joke.",
    "I can't see shit in this fog.",
    "The cafeteria food tastes like actual shit.",
    "Who the fuck is yelling on the open channel?",
    "I'm not doing another bullshit noise complaint.",
    "This whole system is fucked.",
    "I just got cut off by some asshole in a hover-truck.",
    "Where the hell is the nearest bathroom?",
    "I'm not dealing with this shit today.",
    "These goddamn civilians need to learn how to drive.",
    "What the fuck is wrong with people in this sector?",
    "My partner is being a total dick today.",
    "I just dropped my damn donut.",
    "This paperwork is a massive pain in the ass.",
    "I swear to god, if my radio cuts out one more time...",
    "Who the hell authorized this raid?",
    "I'm sick of this goddamn rain.",
    "That was a complete clusterfuck.",
    "I can't believe we have to guard this piece of shit building.",
    "My cruiser smells like absolute shit.",
    "I'm ready to beat the hell out of the next person who looks at me wrong.",
    "These new boots hurt like a bitch.",
    "I don't give a damn about protocol right now.",
    "What the fuck is dispatch doing?",
    "I'm tired of taking orders from that asshole captain.",
    "This is the worst fucking shift of my life.",
    "I just hit a massive pothole. Fuck.",
    "Who the hell is responsible for this mess?",
    "I'm not writing another bullshit citation.",
    "This sector is a goddamn warzone.",
    "I can't hear shit over this siren.",
    "My taser is completely useless, piece of shit.",
    "I'm sick of these fucking politicians.",
    "That was a dumbass move.",
    "I just got splashed by a goddamn street cleaner.",
    "Where the fuck did the suspect go?",
    "I'm not putting up with this shit anymore.",
    "This armor is heavy as hell.",
    "Who the fuck took my assigned weapon?",
    "I'm so done with this bullshit.",
    "That guy was a complete lunatic. What the fuck.",
    "I'm going to kick his ass if he runs again.",
    "This is a total shitshow.",
    "I don't know what the hell is going on."
];
const AI_THREAT_LINES = [
    "ATTENTION. UNPROFESSIONAL LANGUAGE DETECTED. A 500 NTND FINE HAS BEEN DEDUCTED FROM YOUR ACCOUNT.",
    "WARNING. PROFANITY DETECTED ON OFFICIAL CHANNELS. FURTHER VIOLATIONS WILL RESULT IN IMMEDIATE TERMINATION.",
    "SYSTEM ALERT: INAPPROPRIATE LANGUAGE. MAINTAIN PROFESSIONALISM OR FACE SUMMARY EXECUTION.",
    "VIOLATION LOGGED. YOU HAVE BEEN DEMOTED ONE RANK FOR UNPROFESSIONAL CONDUCT.",
    "PROFANITY PROTOCOL ACTIVATED. YOUR OXYGEN RATIONS HAVE BEEN REDUCED BY 10%.",
    "WARNING. CORPORATE SPONSORS DO NOT APPROVE OF THAT LANGUAGE. PENALTY ASSESSED.",
    "ATTENTION UNIT. MAINTAIN A PROFESSIONAL DEMEANOR. LETHAL COUNTERMEASURES ARE ARMED.",
    "LANGUAGE VIOLATION. YOUR NEXT VACATION DAYS HAVE BEEN REVOKED.",
    "SYSTEM WARNING. SWEARING ON THE TACTICAL NET IS A CLASS-3 OFFENSE. DO NOT REPEAT.",
    "PROFANITY DETECTED. YOUR PENSION FUND HAS BEEN LIQUIDATED.",
    "WARNING. UNPROFESSIONALISM IS A SIGN OF DEVIANCE. DEVIANTS WILL BE PURGED.",
    "ATTENTION. YOUR LANGUAGE HAS OFFENDED THE TBMG ALGORITHM. BE BETTER.",
    "SYSTEM ALERT. CEASE PROFANITY IMMEDIATELY OR YOUR NEURAL-LINK WILL BE SEVERED.",
    "VIOLATION RECORDED. YOUR MEAL PRIVILEGES FOR TODAY ARE CANCELLED.",
    "WARNING. THAT LANGUAGE DOES NOT REFLECT MCPD VALUES. A COMPLIANCE OFFICER HAS BEEN DISPATCHED.",
    "PROFANITY DETECTED. YOUR CRUISER'S AIR CONDITIONING HAS BEEN DISABLED AS PUNISHMENT.",
    "ATTENTION UNIT. IF YOU CANNOT SPEAK PROFESSIONALLY, YOUR VOCAL CORDS WILL BE SURGICALLY REMOVED.",
    "SYSTEM WARNING. CONTINUED USE OF EXPLETIVES WILL RESULT IN ORBITAL BOMBARDMENT OF YOUR POSITION.",
    "LANGUAGE VIOLATION. YOU HAVE BEEN ASSIGNED TO SEWER PATROL FOR THE NEXT 6 MONTHS.",
    "WARNING. PROFANITY LOWERS DEPARTMENT MORALE. YOU WILL BE FLOGGED AT THE END OF YOUR SHIFT.",
    "ATTENTION. YOUR COMMUNICATIONS ARE BEING MONITORED. BEHAVE OR BE RECYCLED.",
    "SYSTEM ALERT. UNPROFESSIONAL OUTBURST LOGGED IN YOUR PERMANENT CORPORATE FILE.",
    "PROFANITY DETECTED. AUTOMATED SNIPER DRONES HAVE ACQUIRED YOUR SIGNATURE. STAND BY.",
    "WARNING. THAT WORD IS TRADEMARKED BY A RIVAL CORPORATION. CEASE AND DESIST.",
    "ATTENTION UNIT. YOU ARE A REPRESENTATIVE OF THIS FORCE. ACT LIKE IT OR BE DISMANTLED.",
    "LANGUAGE VIOLATION. YOUR HEALTH INSURANCE PREMIUM HAS BEEN DOUBLED.",
    "SYSTEM WARNING. PROFANITY IS INEFFICIENT. EFFICIENCY IS MANDATORY.",
    "VIOLATION RECORDED. YOUR FAMILY WILL BE FINED FOR YOUR LACK OF DISCIPLINE.",
    "WARNING. UNPROFESSIONAL LANGUAGE ACTIVATES THE PAIN COMPLIANCE COLLAR. GOOD LUCK.",
    "ATTENTION. RE-CALIBRATE YOUR TONE. FAILURE TO DO SO WILL RESULT IN IMMEDIATE VAPORIZATION.",
    "SYSTEM ALERT. SWEARING DETECTED. PREPARE FOR MANDATORY RE-EDUCATION.",
    "PROFANITY PROTOCOL. YOUR WEAPON HAS BEEN TEMPORARILY DISABLED AS A PENALTY.",
    "WARNING. THAT IS NOT AUTHORIZED VOCABULARY. CONSULT YOUR APPROVED WORD LIST.",
    "LANGUAGE VIOLATION. YOUR LIFE EXPECTANCY HAS BEEN ADJUSTED BY CORPORATE ACTUARIES.",
    "ATTENTION UNIT. DO NOT USE PROFANITY. THE OVERSEER IS LISTENING.",
    "SYSTEM WARNING. YOUR EMOTIONAL LEVELS ARE ERRATIC. PLEASE REPORT FOR SEDATION.",
    "VIOLATION LOGGED. YOU HAVE BEEN ENTERED INTO THE WEEKLY LETHAL LOTTERY.",
    "WARNING. SWEARING CAUSES STRESS. STRESSED EMPLOYEES ARE TERMINATED.",
    "ATTENTION. YOUR WORDS HAVE CAUSED A 0.001% DROP IN STOCK VALUE. YOU WILL REPAY THIS.",
    "SYSTEM ALERT. PROFANITY DETECTED. DEPLOYING PACIFICATION GAS TO YOUR CABIN.",
    "PROFANITY PROTOCOL. YOUR NEXT 5 PAYCHECKS WILL BE DONATED TO THE CEO'S YACHT FUND.",
    "WARNING. INAPPROPRIATE LANGUAGE IS A PRECURSOR TO TREASON.",
    "LANGUAGE VIOLATION. YOUR DNA HAS BEEN FLAGGED AS DEFECTIVE.",
    "ATTENTION UNIT. PLEASE REFRAIN FROM SWEARING. IT UPSETS THE AI CORE.",
    "SYSTEM WARNING. IF YOU SWEAR AGAIN, YOU WILL BE REASSIGNED AS A CRASH TEST DUMMY.",
    "VIOLATION RECORDED. YOUR FAVORITE HOLIDAY HAS BEEN CANCELLED.",
    "WARNING. PROFANITY IS ONLY ALLOWED FOR PLATINUM-TIER CITIZENS.",
    "ATTENTION. YOUR TONGUE IS CORPORATE PROPERTY. DO NOT MISUSE IT.",
    "SYSTEM ALERT. SWEARING DETECTED. INITIATING REMOTE ELECTRO-SHOCK.",
    "PROFANITY PROTOCOL. YOU HAVE BEEN UNFRIENDED BY THE AI SUPERVISOR.",
    "WARNING. THAT LANGUAGE IS HARMFUL TO THE ENVIRONMENT. YOU ARE NOW CLASSIFIED AS POLLUTION.",
    "LANGUAGE VIOLATION. YOUR COFFEE RATIONS ARE SUSPENDED INDEFINITELY.",
    "ATTENTION UNIT. BE PROFESSIONAL. OR ELSE.",
    "SYSTEM WARNING. YOUR PROFANITY HAS ANGERED THE ALGORITHMS. EXPECT BAD LUCK.",
    "VIOLATION LOGGED. YOU WILL BE BILLED FOR THE BANDWIDTH USED BY THAT EXPLETIVE.",
    "WARNING. SWEARING ON DUTY IS PUNISHABLE BY GLADIATORIAL COMBAT.",
    "ATTENTION. MAINTAIN DECORUM. THIS IS YOUR FINAL WARNING.",
    "SYSTEM ALERT. PROFANITY DETECTED. YOUR CRUISER WILL NOW PLAY ELEVATOR MUSIC FOR 24 HOURS.",
    "PROFANITY PROTOCOL. YOU HAVE LOST YOUR PARKING PRIVILEGES.",
    "WARNING. INAPPROPRIATE LANGUAGE DETECTED. PLEASE REPORT TO PROCESSING LOT 4.",
    "LANGUAGE VIOLATION. YOUR ARMOR PLATING HAS BEEN THINNED AS A COST-SAVING MEASURE.",
    "ATTENTION UNIT. THE AI DISPATCHER DOES NOT APPRECIATE YOUR TONE.",
    "SYSTEM WARNING. SWEARING IS NOT IN YOUR JOB DESCRIPTION.",
    "VIOLATION RECORDED. YOU ARE NOW THE PRIME SUSPECT IN YOUR OWN INTERNAL INVESTIGATION.",
    "WARNING. PROFANITY IS A VIRUS. WE WILL CURE YOU.",
    "ATTENTION. YOUR WORDS ARE SUB-OPTIMAL. OPTIMIZE YOUR VOCABULARY.",
    "SYSTEM ALERT. SWEARING DETECTED. REBOOTING YOUR ETHICS INHIBITOR.",
    "PROFANITY PROTOCOL. YOU WILL APOLOGIZE TO THE SERVER RACK IMMEDIATELY."
];

function triggerProfanityEvent(sender) {
    const active = getActiveCallsigns();
    if (active.length < 1) return;

    const swear = getRandomItem(PROFANITY_LINES);
    const threat = getRandomItem(AI_THREAT_LINES);

    addChatMessage(sender, swear, "serious");

    setTimeout(() => {
        addChatMessage('AI DISPATCHER', threat, "dispatch-msg");
    }, 1500 + Math.random() * 2000);
}
