// MCPD TRANSMISSIONS DATABASE
// All voice lines and chat arrays for officers are stored here for easy editing.

window.jokes = [
    "Just unloaded a full clip into a suspicious garbage can. Area secure.",
    "Anyone else craving donuts right now? I shot a pigeon on the way here.",
    "My trigger finger is getting itchy, any action yet?",
    "If they didn't want to get tased, they shouldn't have looked at me funny.",
    "Current status: drawing weapon on a suspicious shadow.",
    "To the rookie who left their safety on: I'm confiscating your coffee.",
    "Did anyone capture that stray dog? It looked at me aggressive so I deployed less-lethal.",
    "Pick up that can. Haha, always wanted to say that.",
    "Is it just me or does the Chief owe us all a pizza party for the body count this week?",
    "Outbreak, outbreak, outbreak... oh wait, just someone sneezing. Never mind.",
    "My cruiser is making a weird noise. I might just shoot the engine.",
    "If I have to fill out one more use-of-force form today, I'm using force on the printer.",
    "Suspect tripped and fell on my baton. Five times. It was wild.",
    "I'm pretty sure my body cam 'accidentally' turned off again. Standard procedure.",

    // Bizarre Quotes
    "Sometimes, I dream about cheese.",
    "Is the sky actually a holograph? Just wondering while I beat this perp.",
    "I swear my radio just whispered my middle name.",
    "The pavement tastes like pennies today.",
    "Who left a toaster in the evidence locker?",
    "Dispatch, my shadow is moving independently. Please advise.",
    "I think the crows are wiretapping my cruiser.",
    "Do you ever think about how we are all just meat inside a metal cage?",
    "My left shoe has been vibrating for an hour. Code 3.",
    "There's a man made entirely of bees on 3rd street. I'm going to shoot it.",
    "Dispatch, can you confirm if gravity was turned off in sector 7?",
    "I just gave a speeding ticket to a horse.",
    "Can someone bring me a spatula? Tactical reasons.",
    "My reflection just blinked at me.",
    "The suspect turned into a cloud of glitter. Requesting backup.",

    // Half-Life 2 / Combine Random Chatter
    "Anticitizen one located. Prepare for extraction.",
    "Target is infected. Requesting authorization to cauterize the block.",
    "Warning. Primary target has engaged. Returning fire.",
    "Suspect exhibits anti-civil behavior. Sterilizing the area.",
    "Block is hot. Code 3 response authorized.",
    "Confirmed visual on the HVT. Taking the shot.",
    "Overwatch, acknowledge. We are sweeping the sector.",
    "Protection team, alert! We have a containment failure!",
    "Attention ground units. Anti-citizen reported in this community.",
    "Code: isolate, expose, administer.",
    "Amputate.",
    "Cauterize.",
    "Sterilize.",
    "Outland secure is compromised! Repeat, compromised!",
    "Overwatch, requesting reserve activation.",
    "Objective failed. Deploying autonomous units.",
    "Infected zone detected. Containment protocol active.",
    "Despatch, priority target is evading. Send Hunter-Chopper.",
    "All units, converge on position. Expose and amputate.",
    "Suspect is sub-prime. Execute.",
    "You have been convicted of multiple anti-civil violations. Implicit citizenship revoked.",
    "I'm keeping my stun baton charged. Just in case.",
    "Did you hear the new orders? Free fire zone.",
    "I've got a standard issue ration if anyone wants it.",
    "Don't drink the water. They put something in it to make you forget.",

    // Extended Bizarre Quotes
    "I'm currently engaged in a staring contest with a fire hydrant. Backup requested.",
    "Is it protocol to shoot the clouds if it looks like it's going to rain?",
    "Dispatch, my cruiser's steering wheel just turned into a snake. Please advise.",
    "I think the mayor is actually three raccoons in a trench coat. Firing warning shots.",
    "Can someone bring me a net? I'm trying to catch yesterday.",
    "My taser is making a humming noise that sounds like a 90s boy band.",
    "There's a mime resisting arrest in sector 4. I'm trapped in an invisible box!",
    "Dispatch, my coffee is looking at me funny. Permission to neutralize.",
    "I pulled over a guy but he handed me a Monopoly 'Get Out of Jail Free' card. Letting him go.",
    "Does anyone else hear boss music?",
    "I told the perp to freeze, and he threw ice at me. Send backup.",
    "I accidentally handcuffed myself to the steering wheel. Again.",
    "Dispatch, has the sky always been blue or is this a simulation glitch?",
    "Requesting a SWAT team for this spider in my vehicle.",
    "The suspect is throwing existential dread at me. My shields are failing.",
    "My badge just dissolved. Am I still a cop?",
    "I'm responding to a 10-50, but it's just two pigeons fighting over a french fry.",
    "Who replaced my ammo with jellybeans? The suspect is very confused.",
    "I think my shadow is plotting to arrest me.",
    "Dispatch, I shot the sheriff, but I did not shoot the deputy. Awaiting orders.",
    "The suspect's aura is highly illegal. Deploying spiritual crystals.",
    "Has anyone seen my sanity? I think I dropped it near 5th and Main.",
    "I arrested a toaster for burning my bagel. It's doing 5 to 10 now.",

    // Extended Half-Life 2 Quotes
    "Memory replacement is the first step toward true citizenship.",
    "Attention please. Evasion of containment is a capital offense.",
    "Citizen notice: Failure to cooperate will result in permanent off-world relocation.",
    "You have been charged with socio-endangerment level 5.",
    "Prepare to receive civil judgment.",
    "Individual, you are charged with multiple counts of anti-civil behavior.",
    "Security alert. Illegal broadcast detected.",
    "Overwatch acknowledges critical existence failure.",
    "Viscerator deployed. Searching.",
    "Contact with malignant virus confirmed.",
    "Attention ground units. Anti-citizen reported in this community.",
    "All units, code: sacrifice, coagulate, plan.",
    "Report all socio-behavioral anomalies to your local Civil Protection team.",
    "Your implicit citizenship has been revoked.",
    "Unit down. Requesting heavily armed response.",
    "We have a localized bio-hazard. Sterilize the sector.",
    "Non-compliant citizens will be processed and re-educated.",
    "Target is infected. Purging.",
    "Overwatch, we have a breach in the perimeter.",
    "Attention residents. This block contains potential infection. Stay in your homes.",
    "Civil Protection reminds you that unauthorized reproductive simulation is a level 3 offense.",
    "Overwatch reports possible hostiles in the underground sub-levels.",
    "Code: amputate, zero, confirm.",
    "Executing standard pacification protocol.",
    "Malignant engagement resolved. Sector is returning to standard civil index.",
    "Miscount detected in your block. Co-operation with your Civil Protection team permits full ration reward."
];

window.seriousChats = [
    "Subject reached for waistband, suspect neutralized. Send EMS and the cleanup crew.",
    "Deploying less-lethal... scratch that, deploying lethal.",
    "Perimeter secure. 4 suspects down. Looks like they resisted arrest.",
    "We have a 10-50, driver was non-compliant, vehicle disabled via gunfire.",
    "Copy that dispatch, weapons drawn, proceeding to target.",
    "I have visual on the described vehicle. Requesting authorization to pit and fire.",
    "Requesting backup for a high-risk stop, Highway 4. Bring the heavy ordinance.",
    "Overwatch, acknowledge. We are sweeping the sector."
];

window.worriedChats = [
    "What the hell is going on out there? I need more ammo over here!",
    "Dispatch, are we under attack? I'm firing at everything that moves.",
    "I'm out of clips! We need a resupply drop right now!",
    "This is getting insane. I've never seen so many officers triggering distress.",
    "Do we have MaxTac on standby? Because we need them immediately.",
    "I'm pinned down! Authorize use of orbital strike?",
    "Everybody stay sharp, free fire zone authorized in Sector 4.",
    "Chief needs to get down here right now. We are losing control of the streets.",
    "Dispatch, send every available unit. Tell them to come out with guns blazing.",
    "Protection team, alert! We have a containment failure!",
    "Sector is lost! Requesting immediate air support!",
    "They're everywhere! I'm falling back, covering fire!",
    "Outland secure is compromised! Repeat, compromised!",
    "Requesting reinforcement! My squad is wiped out!",
    "I don't want to die doing paperwork! Send the heavy synths!"
];

window.reactionNormalChats = [
    "10-4, Dispatch. Weapons hot.",
    "Copy that. Engaging.",
    "Understood, Dispatch. Lock and load.",
    "10-4, showing received. Going tactical.",
    "Loud and clear. Target acquired.",
    "Copy, proceeding with extreme prejudice.",
    "Affirmative. Sterilizing area now.",
    "Roger that. Containment team moving in."
];

window.reactionCrazyChats = [
    "Dispatch, are you okay? Should I shoot the terminal?",
    "10-9 Dispatch, your transmission was garbled. Authorization to use force unclear.",
    "Did you just have a stroke on the keyboard, Dispatch? Do I shoot or not?",
    "Uh, Dispatch... do you need us to send EMS or a SWAT team to the comms center?",
    "Who is operating the console right now? Sounded like a cyber-psycho.",
    "Dispatch, please lay off the stims.",
    "I think the dispatch terminal has a virus. Let me shoot it.",
    "10-9? Sounded like you were just mashing buttons. I'm taking cover.",
    "Warning: anomalous communication detected. Preparing to purge the network.",
    "Dispatch, is this a loyalty test? Because I'll shoot whoever you want."
];

window.voreChats = [
    "Dispatch... what is happening? The walls are breathing.",
    "I don't feel safe out here anymore. Something is hunting us.",
    "Did anyone just see the sky blink?",
    "My cruiser's dashboard is melting... or am I going crazy?",
    "I need backup! Not for criminals... for the shadows. They're moving.",
    "Dispatch, my reflection in the mirror just smiled at me. I'm leaving.",
    "Is anyone else hearing that low hum? It's inside my skull.",
    "I swear the pavement just swallowed a stray dog.",
    "I want to go home, Dispatch. Please let us go home.",
    "They told us we'd be protecting the city. They didn't tell us from what.",
    "I'm locking myself in the trunk. Do not send anyone.",
    "The streetlights are all pointing at me.",
    "My sidearm just whispered my name.",
    "There are teeth in the concrete. Huge teeth.",
    "I'm staring into the alleyway and it's staring back.",
    "Dispatch, please wake me up. I know this is a dream. Wake me up!",
    "The rain smells like copper today.",
    "I just saw my own corpse walking down 4th street.",
    "Something is under the city. It's waking up.",
    "My partner vanished when I blinked.",
    "I'm not shooting anyone. I don't want to make it angry.",
    "Every civilian face is completely blank. No eyes. No mouths.",
    "The radio static sounds like screaming... is that you, Dispatch?",
    "I can't remember my own name anymore. Where am I?",
    "Did the sun just turn black?",
    "We are not in control. We never were.",
    "I found a door in the middle of the street. It's open.",
    "Gravity feels... optional right now.",
    "They're coming from the sewers. Millions of them. But they look like us.",
    "I just arrested a shadow. My cuffs went right through it.",
    "Who is Gordon Freeman? Why does my brain hurt when I say it?",
    "My blood is turning cold. I think I died yesterday.",
    "I beg you, send an extraction team! But don't let them look at the sky!",
    "The neon signs are spelling out my sins.",
    "I'm hiding under the cruiser. Tell my family to forget me.",
    "My weapon is useless against this.",
    "I fired a full mag into it... it just absorbed the bullets.",
    "We breached the apartment, but the geometry inside is all wrong. Endless hallways.",
    "There's a knock on the patrol car window. But I'm parked on a bridge. Over the water.",
    "The sirens sound like laughing.",
    "I'm taking off my badge. This is not our city anymore.",
    "The birds. Look at the birds. They're completely frozen in mid-air.",
    "I tried to run, but everywhere I go, I end up back here.",
    "It's too quiet. Even the wind stopped.",
    "My heart isn't beating, Dispatch. I checked three times.",
    "We're just food. That's all we are.",
    "The buildings are leaning over, trying to crush us.",
    "I can hear the city thinking.",
    "Don't trust unit 47. He has entirely too many joints in his arms now.",
    "I'm dropping my weapon and walking into the fog. Good luck."
];

window.greetingChats = [
    "Hey! Anyone want to grab coffee near Sector 4?",
    "Yo, how's the patrol going?",
    "Just clocked in. What did I miss?",
    "Sup guys, another beautiful day in the dystopia.",
    "Hello from the east district. Quiet tonight.",
    "Greetings, fellow enforcers.",
    "Hey! Stop hogging the radio.",
    "Anyone got eyes on that stolen hover-car?",
    "Morning! If you can call it morning through the smog.",
    "Howdy! Watch out for the potholes on 9th ave.",
    "Hey man, I heard you got promoted!",
    "Yo! Just got a fresh supply of stun batons.",
    "Hello everyone! Keep your heads down today.",
    "Hey! Need backup over here just to eat my donut in peace.",
    "Sup! Did you finish that paperwork from yesterday?",
    "Greetings from the holding cells. It's loud in here.",
    "Hey, buddy! Long time no see on the dispatch channel.",
    "Yo! Who's buying lunch today?",
    "Hi guys! Stay alert out there.",
    "Hey! My cruiser's AC is broken again.",
    "Sup! Just chasing down some petty thieves.",
    "Hello! Anybody else bored out of their mind?",
    "Hey man, watch your six in the industrial zone.",
    "Yo! Let's wrap this shift up quick.",
    "Hi! Checking in from the rooftop patrol.",
    "Hey! Have you seen the new rookie? Absolute mess.",
    "Sup! I need a coffee IV drip right now.",
    "Hello from the traffic division! Send help, it's terrible.",
    "Hey! Don't let the captain catch you sleeping.",
    "Yo! What's the bounty on Freeman up to now?",
    "Hi guys, keep the chatter down, I have a headache.",
    "Hey! Anyone want to swap shifts on Friday?",
    "Sup! Just cleared a squatter camp.",
    "Hello! This radio is full of static.",
    "Hey man, keep your vest tight.",
    "Yo! First one back to the precinct wins a prize.",
    "Hi! My taser is acting up today.",
    "Hey! Let's go bust some skulls.",
    "Sup! Anyone else feel like we're just pawns in a simulation?",
    "Hello! Ready for some action.",
    "Hey! Got my eyes peeled.",
    "Yo! Check out the cyberware on that guy.",
    "Hi! Reporting for duty.",
    "Hey! Let's make this city safe.",
    "Sup! Another day, another dollar... wait, we use credits.",
    "Hello! Stay safe out there.",
    "Hey! Keep your comms linked.",
    "Yo! See you at the briefing.",
    "Hi! Over and out for a coffee break.",
    "Hey! Good luck on patrol."
];

window.yellLines = [
                "Clear the channel! Both of you! Act like professionals!",
                "Cut the chatter! This is an official frequency!",
                "If you two don't shut up, I'm writing you both up. Clear the air!",
                "Enough! Keep the channel clear for actual emergencies!"
            ];

window.banterLines = [
                "Man, the synth-rations at the precinct taste like cardboard today.",
                "Anyone want to trade shifts on Friday? I need to get out of this sector.",
                "I swear my cruiser's AC is blowing hot air again.",
                "Did you see that new cyberware ad? Total ripoff.",
                "I'm so tired I could sleep standing up.",
                "If dispatch gives me one more noise complaint, I'm quitting."
            ];

window.wantedLines = [
                            `Dispatch, I just had a run-in with {name}. I'm flagging them as Wanted. Total scum.`,
                            `{name} just pulled a weapon and ran. Declaring them Wanted!`,
                            `Putting out a warrant for {name}. They're on the Wanted list now.`,
                            `Be advised, {name} is now considered Armed and Wanted in my sector.`
                        ];

window.suspLines = [
                            `This guy {name} bumped into me. Declaring him Suspicious.`,
                            `Dispatch, {name} is acting extremely erratic. Marking them Suspicious in the directory.`,
                            `Got my eye on {name}. Putting a Suspicious flag on their dossier.`,
                            `{name} refused to answer questions. They're Suspicious now.`
                        ];


