// MCPD TRANSMISSIONS DATABASE
// All voice lines and chat arrays for officers are stored here for easy editing.

window.jokes = [
    "Just pulled over a hoverboard for speeding. The future is weird.",
    "Anyone else's taser smell like burnt toast?",
    "I tried to arrest a rogue AI today. It argued jurisdiction.",
    "Do we get overtime for existential dread?",
    "My cruiser is out of gas, I'm going to Flintstones it.",
    "I just gave a parking ticket to a cloud of smoke.",
    "Suspect tried to bribe me with crypto. I only take hard cash.",
    "Dispatch, my uniform shrank in the wash. I need backup.",
    "I think my K-9 unit is judging me.",
    "Can we replace the sirens with heavy metal music? It's more intimidating.",
    "I accidentally handcuffed myself to the steering wheel. Again.",
    "I just saw a rat carrying a slice of pizza. That's my new spirit animal.",
    "Is it too early to call in a sick day for tomorrow?",
    "I'm considering writing a memoir: 'Confessions of a Trigger Happy Cop'.",
    "I just tried to pull over a pigeon. It flipped me the bird.",
    "Does anyone know if our health insurance covers cybernetic implants?",
    "I found a box of old floppy disks. Anyone know what these are?",
    "Suspect is wearing a tinfoil hat. I'm taking precautions.",
    "I'm out of coffee. This is a Code 10 emergency.",
    "I think I just arrested a time traveler. He kept asking what year it is.",
    "My partner is asleep in the passenger seat. Should I brake check?",
    "I just wrote a citation for 'excessive loitering'.",
    "Is it illegal to use the siren to get through traffic to the donut shop?",
    "I found a stray cat. It's my new partner.",
    "I think the vending machine at the precinct is plotting against me.",
    "Suspect is unarmed but very sarcastic. Requesting permission to tase.",
    "I just stepped in a puddle of something glowing. Standard Monday.",
    "My radio is picking up a local sports broadcast.",
    "I tried to use the new tactical flashlight. I blinded myself.",
    "I'm considering a transfer to the cyber-crimes division. I like sitting.",
    "I just saw a drone deliver a pizza. I intercepted the pizza.",
    "Does anyone have a charger for a standard issue taser?",
    "I think my vest is on backwards.",
    "Suspect is reciting poetry. It's terrible poetry. Moving to apprehend.",
    "I just found a perfectly good sandwich on the hood of my car.",
    "I'm petitioning the Chief for tactical capes.",
    "I think the dispatch AI is flirting with me.",
    "Suspect is attempting to hide behind a very small bush.",
    "I just realized I haven't blinked in three hours.",
    "Is it considered use of force if I just yell really loud?",

    "Just ticketed a parked car for resisting arrest. Standard protocol.",
    "I think my taser is broken, it keeps playing elevator music when I pull the trigger.",
    "Anyone want to trade a 9mm mag for a half-eaten sandwich? Asking for a friend.",
    "Suspect fled the scene on a motorized scooter. I called in an airstrike.",
    "I accidentally pepper-sprayed myself. Can someone bring milk? Lots of milk.",
    "Is it against regulations to use a flashbang as a reading light? Asking for a rookie.",
    "My cruiser's AC is broken. I'm going to start shooting at the sun.",
    "I found a box of old VHS tapes in the evidence locker. Movie night at precinct 9!",
    "Does anyone know how to get blood out of synthetic leather? Fast?",
    "Suspect threw a book at me. I charged them with assault with a deadly narrative.",
    "Dispatch, can you order me a pizza? I'm technically on a high-speed chase but I'm hungry.",
    "I just pulled over a guy driving a lawnmower. He had a warrant. And a great lawn.",
    "I'm out of ammo. I'm just going to throw my badge at them really hard.",
    "Does anyone else hear boss music?",
    "I just witnessed a crime but I was on break. So I didn't.",
    "I'm considering a career change. Maybe something less violent, like a butcher.",
    "My partner just tried to arrest a mirror. It's been a long shift.",
    "Just found out the Chief is my dad. Weird day.",
    "I think I left my gun in the bathroom. If anyone finds it, it's the one with the scratch on the barrel.",
    "Suspect is doing jumping jacks. Should I engage?",
    "I'm not saying I'm bored, but I just gave a squirrel a citation.",
    "Is it Tuesday? It feels like a Tuesday.",
    "I just ate a donut off the floor. Don't tell Internal Affairs.",
    "My body armor is itching. I think I'm allergic to justice.",
    "I'm starting to think the badge is just a heavy piece of metal.",

    "Just unloaded a full clip into a suspicious garbage can. Area secure.",
    "Anyone else craving donuts right now? I shot a pigeon on the way here.",
    "My trigger finger is getting itchy, any action yet?",
    "If they didn't want to get tased, they shouldn't have looked at me funny.",
    "Current status: drawing weapon on a suspicious shadow.",
    "To the rookie who left their safety on: I'm confiscating your coffee.",
    "Did anyone capture that stray dog? It looked at me aggressive so I deployed less-lethal.",
    "Pick up that can. Haha, always wanted to say that.",
    "Is it just me or does the Chief owe us all a pizza party for the body count this week?",
    "Outbreak, outbreak, outbreak... oh wait, just someone sneezing. Never mind.",
    "My cruiser is making a weird noise. I might just shoot the engine.",
    "If I have to fill out one more use-of-force form today, I'm using force on the printer.",
    "Suspect tripped and fell on my baton. Five times. It was wild.",
    "I'm pretty sure my body cam 'accidentally' turned off again. Standard procedure.",

    // Bizarre Quotes
    "Sometimes, I dream about cheese.",
    "Is the sky actually a holograph? Just wondering while I beat this perp.",
    "I swear my radio just whispered my middle name.",
    "The pavement tastes like pennies today.",
    "Who left a toaster in the evidence locker?",
    "Dispatch, my shadow is moving independently. Please advise.",
    "I think the crows are wiretapping my cruiser.",
    "Do you ever think about how we are all just meat inside a metal cage?",
    "My left shoe has been vibrating for an hour. Code 3.",
    "There's a man made entirely of bees on 3rd street. I'm going to shoot it.",
    "Dispatch, can you confirm if gravity was turned off in sector 7?",
    "I just gave a speeding ticket to a horse.",
    "Can someone bring me a spatula? Tactical reasons.",
    "My reflection just blinked at me.",
    "The suspect turned into a cloud of glitter. Requesting backup.",

    // Half-Life 2 / Combine Random Chatter
    "Anticitizen one located. Prepare for extraction.",
    "Target is infected. Requesting authorization to cauterize the block.",
    "Warning. Primary target has engaged. Returning fire.",
    "Suspect exhibits anti-civil behavior. Sterilizing the area.",
    "Block is hot. Code 3 response authorized.",
    "Confirmed visual on the HVT. Taking the shot.",
    "Overwatch, acknowledge. We are sweeping the sector.",
    "Protection team, alert! We have a containment failure!",
    "Attention ground units. Anti-citizen reported in this community.",
    "Code: isolate, expose, administer.",
    "Amputate.",
    "Cauterize.",
    "Sterilize.",
    "Outland secure is compromised! Repeat, compromised!",
    "Overwatch, requesting reserve activation.",
    "Objective failed. Deploying autonomous units.",
    "Infected zone detected. Containment protocol active.",
    "Despatch, priority target is evading. Send Hunter-Chopper.",
    "All units, converge on position. Expose and amputate.",
    "Suspect is sub-prime. Execute.",
    "You have been convicted of multiple anti-civil violations. Implicit citizenship revoked.",
    "I'm keeping my stun baton charged. Just in case.",
    "Did you hear the new orders? Free fire zone.",
    "I've got a standard issue ration if anyone wants it.",
    "Don't drink the water. They put something in it to make you forget.",

    // Extended Bizarre Quotes
    "I'm currently engaged in a staring contest with a fire hydrant. Backup requested.",
    "Is it protocol to shoot the clouds if it looks like it's going to rain?",
    "Dispatch, my cruiser's steering wheel just turned into a snake. Please advise.",
    "I think the mayor is actually three raccoons in a trench coat. Firing warning shots.",
    "Can someone bring me a net? I'm trying to catch yesterday.",
    "My taser is making a humming noise that sounds like a 90s boy band.",
    "There's a mime resisting arrest in sector 4. I'm trapped in an invisible box!",
    "Dispatch, my coffee is looking at me funny. Permission to neutralize.",
    "I pulled over a guy but he handed me a Monopoly 'Get Out of Jail Free' card. Letting him go.",
    "Does anyone else hear boss music?",
    "I told the perp to freeze, and he threw ice at me. Send backup.",
    "I accidentally handcuffed myself to the steering wheel. Again.",
    "Dispatch, has the sky always been blue or is this a simulation glitch?",
    "Requesting a SWAT team for this spider in my vehicle.",
    "The suspect is throwing existential dread at me. My shields are failing.",
    "My badge just dissolved. Am I still a cop?",
    "I'm responding to a 10-50, but it's just two pigeons fighting over a french fry.",
    "Who replaced my ammo with jellybeans? The suspect is very confused.",
    "I think my shadow is plotting to arrest me.",
    "Dispatch, I shot the sheriff, but I did not shoot the deputy. Awaiting orders.",
    "The suspect's aura is highly illegal. Deploying spiritual crystals.",
    "Has anyone seen my sanity? I think I dropped it near 5th and Main.",
    "I arrested a toaster for burning my bagel. It's doing 5 to 10 now.",

    // Extended Half-Life 2 Quotes
    "Memory replacement is the first step toward true citizenship.",
    "Attention please. Evasion of containment is a capital offense.",
    "Citizen notice: Failure to cooperate will result in permanent off-world relocation.",
    "You have been charged with socio-endangerment level 5.",
    "Prepare to receive civil judgment.",
    "Individual, you are charged with multiple counts of anti-civil behavior.",
    "Security alert. Illegal broadcast detected.",
    "Overwatch acknowledges critical existence failure.",
    "Viscerator deployed. Searching.",
    "Contact with malignant virus confirmed.",
    "Attention ground units. Anti-citizen reported in this community.",
    "All units, code: sacrifice, coagulate, plan.",
    "Report all socio-behavioral anomalies to your local Civil Protection team.",
    "Your implicit citizenship has been revoked.",
    "Unit down. Requesting heavily armed response.",
    "We have a localized bio-hazard. Sterilize the sector.",
    "Non-compliant citizens will be processed and re-educated.",
    "Target is infected. Purging.",
    "Overwatch, we have a breach in the perimeter.",
    "Attention residents. This block contains potential infection. Stay in your homes.",
    "Civil Protection reminds you that unauthorized reproductive simulation is a level 3 offense.",
    "Overwatch reports possible hostiles in the underground sub-levels.",
    "Code: amputate, zero, confirm.",
    "Executing standard pacification protocol.",
    "Malignant engagement resolved. Sector is returning to standard civil index.",
    "Miscount detected in your block. Co-operation with your Civil Protection team permits full ration reward."
,
"I just mag-dumped into a shadow. Looked like it had a gun. Can someone bring me more ammo?",
"Oops, I think my safety was off. Oh well, less paperwork if they don't survive to complain.",
"Suspect gave me a dirty look. I gave him a hollow point. Fair trade.",
"I didn't open fire for no reason, Dispatch. The reason is that I was bored.",
"If they didn't want to get shot, they shouldn't have been in my line of sight.",
"Wait, we're supposed to give verbal warnings *before* we shoot? My bad.",
"Just deployed a flashbang into a parked car. Kept looking at me funny.",
"My trigger finger was cramping, had to stretch it out. Suspect got in the way.",
"Is there a high score for most rounds fired in a single shift? Because I think I just beat it.",
"Dispatch, put me down for a 10-8. Also, send a cleaning crew to 5th avenue. Don't ask.",
"I fired a warning shot! It just happened to hit them in the center mass.",
"He was aggressively jaywalking! I had no choice but to deploy lethal force.",
"I thought his cell phone was a heavy ordnance weapon. Honest mistake.",
"Does the department pay for therapy? Not for me, for the guy I just arrested.",
"I'm out of beanbags, so I just used real bullets. Same difference, right?",
"The suspect tripped and fell on my bullets. Repeatedly.",
"Can we get a drive-thru ammo resupply? I'm tapped out already.",
"I didn't shoot him! My gun just sneezed.",
"I sprinkled some crack on him after the fact. Standard procedure.",
"Listen, if I have to fill out use of force paperwork anyway, I might as well get my money's worth.",
"I'm establishing a strict shoot-first, ask-questions-never policy in Sector 4.",
"Whoops, my finger slipped. 15 times.",
"Dispatch, I shot the suspect. Yes, the one who was already in handcuffs. He looked shifty.",
"If the Chief asks, the suspect was resisting. I don't care if he was unconscious.",
"I find that suspects are a lot more compliant when they have bullet holes in them.",
"I'm just doing my part to keep the local hospital in business."
,
"Dispatch, I'm eating the evidence. It tastes like purple.",
"I just arrested a stop sign for resisting. It's in the back of the cruiser now.",
"If I scream into the radio, do you hear it in your teeth?",
"The suspect was made of liquid, so I drank him. Code 4.",
"I've decided I'm not a cop anymore. I am a feral raccoon. Over.",
"I just put handcuffs on my own shadow. Requesting backup, it's strong.",
"Dispatch, do you think the moon hates us? I'm going to fire a warning shot at it.",
"I'm currently pulling over a ghost for speeding. He's being very uncooperative.",
"My teeth are vibrating to the frequency of the radio. Make it stop.",
"I just performed a pit maneuver on a civilian who was walking. The squad car is totaled.",
"Does anyone else hear the sirens, or is that just the screaming in my head again?",
"I found a pile of teeth in the alleyway. I'm keeping them.",
"Dispatch, I replaced my service weapon with a brick. It's much more effective.",
"I just issued a citation to a puddle of water for loitering.",
"The suspect looked at me with his eyes, so I took them.",
"I'm currently communicating via telepathy. If you can't hear this, you're fired.",
"I just wrote a parking ticket in blood. Whose blood? Don't ask.",
"My patrol car is slowly filling with sand and I refuse to roll the windows down.",
"Dispatch, I have arrested myself for thinking about committing a crime. Send a transport.",
"I'm hiding in the ceiling of the precinct. Don't look up.",
"I just threw my radio into the sewer. Talk to me through the drain pipes.",
"The pavement is too soft today. I don't trust it. Requesting an airlift.",
"I stared at a civilian until they cried. Just standard community outreach.",
"I'm legally changing my callsign to 'The Flesh Devourer'. Please update the CAD.",
"I shot the suspect because he had an ugly shirt. It was an aesthetic emergency."
];

window.seriousChats = [
    "Unit responding. ETA 2 minutes.",
    "We have established a perimeter. Awaiting orders.",
    "Suspect description confirmed. Engaging.",
    "We need a forensics team at this location.",
    "Area is clear. No signs of the suspect.",
    "Dispatch, run a background check on this ID.",
    "We have a hostage situation. Requesting negotiators.",
    "Suspect is armed with high-caliber weaponry.",
    "We are sweeping the building, floor by floor.",
    "I need a K-9 unit at my location.",
    "We have a visual on the target. Holding position.",
    "Suspect is uncooperative. Applying restraints.",
    "We need air support to track the fleeing vehicle.",
    "Dispatch, initiate a city-wide BOLO.",
    "We found a stash of illegal cybernetics.",
    "Area secured. Awaiting transport for the suspect.",
    "We have a 10-33 in progress. Need backup.",
    "Suspect is barricaded. Preparing to breach.",
    "We need the bomb squad down here. Found a suspicious package.",
    "Dispatch, trace this comm frequency.",
    "We have multiple casualties. Expedite medical.",
    "Suspect is attempting to access restricted servers.",
    "We are maintaining radio silence. Over.",
    "I need a drone sweep of the immediate area.",
    "Suspect has a history of violent offenses.",
    "We are engaging the target. Cover me.",
    "Dispatch, we need a containment team for this anomaly.",
    "We have secured the evidence. Chain of custody maintained.",
    "Suspect is injured. Requesting medevac.",
    "We are setting up a roadblock on 7th avenue.",
    "Dispatch, confirm the ROE for this engagement.",
    "We have a confirmed positive ID.",
    "Suspect is utilizing active camouflage. Use thermal optics.",
    "We need to evacuate this block immediately.",
    "Dispatch, log this as a Code 4. Situation resolved.",
    "We are interrogating the suspect on site.",
    "I need a tactical overlay of this building.",
    "Suspect is attempting to flee into the sewers.",
    "We have a high-value target in sight.",
    "Dispatch, situation is critical. Send everything.",

    "Unit 4 responding to a 10-31. Area secured.",
    "Suspect apprehended. Proceeding with booking protocol.",
    "We have a situation on 5th and Main. Requesting backup.",
    "Perimeter established. No civilians in the hot zone.",
    "Target is armed. Proceeding with caution.",
    "Dispatch, be advised, multiple hostiles reported in sector 7.",
    "I have visual on the suspect. Moving to intercept.",
    "Situation is escalating. Lethal force may be required.",
    "All units, be on the lookout for a stolen vehicle matching the description.",
    "We need medical down here immediately. Officer is injured.",
    "Holding position. Awaiting further instructions.",
    "Suspect is barricaded. Requesting SWAT intervention.",
    "We've located the contraband. Securing the evidence.",
    "Interrogation complete. Suspect is not cooperating.",
    "Dispatch, I need a status update on the backup units.",
    "We're sweeping the building now. Keep the channel clear.",
    "Target is on the move. Initiating pursuit.",
    "We have a confirmed casualty. Securing the scene.",
    "Suspect is in custody. Returning to precinct.",
    "We need a perimeter set up a two-block radius from this location.",
    "Dispatch, confirm the warrant on the suspect.",
    "We're taking fire! Need immediate assistance!",
    "Situation is under control. Standing down.",
    "We found a weapon matching the description.",
    "Suspect is attempting to flee on foot. In pursuit.",
    "We need to establish a command post at this location.",
    "Dispatch, I need an ambulance at my location ASAP.",

    "Subject reached for waistband, suspect neutralized. Send EMS and the cleanup crew.",
    "Deploying less-lethal... scratch that, deploying lethal.",
    "Perimeter secure. 4 suspects down. Looks like they resisted arrest.",
    "We have a 10-50, driver was non-compliant, vehicle disabled via gunfire.",
    "Copy that dispatch, weapons drawn, proceeding to target.",
    "I have visual on the described vehicle. Requesting authorization to pit and fire.",
    "Requesting backup for a high-risk stop, Highway 4. Bring the heavy ordinance.",
    "Overwatch, acknowledge. We are sweeping the sector."
];

window.worriedChats = [
    "I've never seen anything like this! What is it?!",
    "We're taking heavy fire! We need backup now!",
    "My HUD is glitching! I can't see anything!",
    "The suspect just jumped a 20-foot wall!",
    "They're not going down! I emptied my mag!",
    "I think we're being hunted! I hear them moving!",
    "My partner is unresponsive! Help!",
    "The building is wired with explosives! Get us out of here!",
    "They hacked our comms! They're listening!",
    "I'm bleeding out! I need a medic!",
    "There are too many of them! We're overrun!",
    "The suspect is a cyborg! Standard rounds are bouncing off!",
    "I lost my weapon! I'm completely unarmed!",
    "They have a hostage! We can't shoot!",
    "I'm trapped in the alley! They're closing in!",
    "My squad car is on fire! We are on foot!",
    "I don't think I'm going to make it back to the precinct...",
    "They are using some kind of neuro-toxin! I can't breathe!",
    "I'm seeing ghosts... the shadows are attacking!",
    "We need an airstrike on this position! Do it now!",
    "They are everywhere! It's an ambush!",
    "My cybernetics are failing! I'm losing control!",
    "I can't stop the bleeding! Oh god!",
    "They are monstrous! What did they do to themselves?!",
    "I'm falling back to a defensible position!",
    "We are completely cut off! No way out!",
    "The suspect just vanished! Into thin air!",
    "I'm scared, Dispatch... I'm really scared.",
    "They have heavy artillery! We are outgunned!",
    "I need an evac right now! NOW!",
    "My armor is breached! I'm exposed!",
    "They are ripping through the blast doors!",
    "I can't hold them! I can't hold them!",
    "The whole block is rigged to blow!",
    "I'm the only one left... everyone else is down.",
    "They are coming for me! I can hear them!",
    "I need a miracle down here, Dispatch!",
    "It's a slaughter! It's an absolute slaughter!",
    "Please... tell my family I love them...",
    "God help us all!",

    "They are everywhere! We can't hold them off much longer!",
    "I'm out of ammo! Requesting immediate resupply!",
    "My partner is down! I repeat, officer down!",
    "They have heavy weapons! We need SWAT now!",
    "I don't think we're going to make it out of here...",
    "There's too many of them! We need to retreat!",
    "My comms are failing! Dispatch, do you read me?!",
    "They're flanking us! Watch your six!",
    "I'm hit! I'm hit! Send medical!",
    "We're pinned down! We can't move!",
    "The building is collapsing! We need to evacuate!",
    "They have a hostage! We can't engage!",
    "I lost visual on the suspect! They could be anywhere!",
    "My weapon jammed! I'm defenseless!",
    "They are using some kind of unknown tech! We are outmatched!",
    "The suspect is heavily augmented! Standard weapons are ineffective!",
    "We are surrounded! There's no way out!",
    "They're hacking our systems! We're losing control!",
    "I'm falling back! I can't hold this position!",
    "We need air support! Now!",
    "They are not human! I repeat, they are not human!",
    "I'm seeing things... the shadows are moving!",
    "They know our names! How do they know our names?!",
    "I can't feel my legs... please, tell my family...",
    "The darkness is closing in... I can't see anything!",
    "They are coming through the walls!",
    "It's a trap! Get out of there!",

    "What the hell is going on out there? I need more ammo over here!",
    "Dispatch, are we under attack? I'm firing at everything that moves.",
    "I'm out of clips! We need a resupply drop right now!",
    "This is getting insane. I've never seen so many officers triggering distress.",
    "Do we have MaxTac on standby? Because we need them immediately.",
    "I'm pinned down! Authorize use of orbital strike?",
    "Everybody stay sharp, free fire zone authorized in Sector 4.",
    "Chief needs to get down here right now. We are losing control of the streets.",
    "Dispatch, send every available unit. Tell them to come out with guns blazing.",
    "Protection team, alert! We have a containment failure!",
    "Sector is lost! Requesting immediate air support!",
    "They're everywhere! I'm falling back, covering fire!",
    "Outland secure is compromised! Repeat, compromised!",
    "Requesting reinforcement! My squad is wiped out!",
    "I don't want to die doing paperwork! Send the heavy synths!"
];

window.reactionNormalChats = [
    "Roger that, Dispatch. Understood.",
    "Copy, Dispatch. Will comply.",
    "10-4. Acknowledged.",
    "Affirmative. On it.",
    "Message received. Proceeding as ordered.",
    "Understood. Implementing now.",
    "Copy that. Will update shortly.",
    "Received and understood.",
    "Affirmative. Executing.",
    "10-4, Dispatch. We're on it.",
    "Understood. Maintaining current protocols.",
    "Copy. Adjusting tactics accordingly.",
    "Message received. Standing by.",
    "Affirmative. Proceeding with caution.",
    "10-4. Will advise when complete.",
    "Understood. Thank you, Dispatch.",
    "Copy that. Will coordinate with other units.",
    "Received. Keep us posted.",
    "Affirmative. Moving out.",
    "10-4. We have the situation handled.",
    "Understood. Over and out.",
    "Copy. Will follow up later.",
    "Message received. No further action required.",
    "Affirmative. That is correct.",
    "10-4. Have a good shift, Dispatch.",
    "Understood. Will monitor the situation.",
    "Copy that. We are good to go.",

    "10-4, Dispatch. Weapons hot.",
    "Copy that. Engaging.",
    "Understood, Dispatch. Lock and load.",
    "10-4, showing received. Going tactical.",
    "Loud and clear. Target acquired.",
    "Copy, proceeding with extreme prejudice.",
    "Affirmative. Sterilizing area now.",
    "Roger that. Containment team moving in."
];

window.reactionCrazyChats = [
    "I will be the architect of their destruction!",
    "Let the streets drown in their regret!",
    "I am the alpha and the omega of this precinct!",
    "I will rip the cyberware from their bodies!",
    "The chaos is beautiful! Look at the flames!",
    "I don't need authorization! I am the law!",
    "I will feed them to the stray dogs!",
    "My gun is hungry, and it's time to eat!",
    "I will show them the true meaning of pain!",
    "They are just fragile meatbags! Break them!",
    "I am a demon of justice! Fear me!",
    "I will dance on the ashes of their criminal empire!",
    "No survivors! Leave no one breathing!",
    "I can smell their fear, and it intoxicates me!",
    "I will crush their skulls like cheap plastic!",
    "Let the sirens sing the song of their demise!",
    "I am untouchable! I am a god among men!",
    "I will paint the precinct red with their blood!",
    "They will beg, but I will only laugh!",
    "I am the storm that will wipe them out!",
    "Break their bones! Shatter their resolve!",
    "I will turn this city into a graveyard!",
    "I am the monster they warned you about!",
    "I will tear their souls from their bodies!",
    "Let the bodies hit the floor! All of them!",
    "I am the judge, jury, and executioner!",
    "I will silence their screams forever!",
    "I am the embodiment of pure vengeance!",
    "Let the carnage begin! I am ready!",
    "I will leave nothing but scorched earth!",
    "They are nothing! I am everything!",
    "I will watch the light fade from their eyes!",
    "I am the apex predator of this city!",
    "I will break them piece by piece!",
    "Let the violence consume us all!",
    "I am the chosen one! I bring the end!",
    "I will bathe in the blood of the corrupted!",
    "They are a disease, and I am the cure!",
    "I will bring the apocalypse to their doorstep!",
    "Hahahahaha! Die! Die! DIE!",

    "Yes! YES! Let the chaos consume them!",
    "I will bathe in the blood of the guilty!",
    "The voices told me to do it. And I agree with them.",
    "I am the law! I am the executioner!",
    "Hahahahaha! Did you see how they exploded?!",
    "I can taste the fear in the air. It's delicious.",
    "They are all insects! I will crush them!",
    "The streets will run red with their compliance!",
    "I am a god of justice! Bow before me!",
    "More! Give me more targets! I need more!",
    "I love the smell of ozone and burnt flesh in the morning.",
    "I will tear them apart with my bare hands!",
    "They will beg for mercy, and I will whisper 'no'.",
    "I am the storm! I am the fury!",
    "Burn it all down! Let the ashes purify this city!",
    "I can see the matrix! I can see their souls breaking!",
    "I am the instrument of their destruction!",
    "They thought they could hide from me? Pathetic.",
    "I will make them suffer for their insolence!",
    "The screams are music to my ears!",
    "I will paint the walls with their regret!",
    "I am unstoppable! I am invincible!",
    "They are nothing but target practice!",
    "I will break them until there is nothing left!",
    "The void calls to me, and I answer with lead!",
    "I am the nightmare they deserve!",
    "Hahahahaha! More! MORE!",
    "I will show them true terror!",
    "They are meat! Just meat for the grinder!",

    "Dispatch, are you okay? Should I shoot the terminal?",
    "10-9 Dispatch, your transmission was garbled. Authorization to use force unclear.",
    "Did you just have a stroke on the keyboard, Dispatch? Do I shoot or not?",
    "Uh, Dispatch... do you need us to send EMS or a SWAT team to the comms center?",
    "Who is operating the console right now? Sounded like a cyber-psycho.",
    "Dispatch, please lay off the stims.",
    "I think the dispatch terminal has a virus. Let me shoot it.",
    "10-9? Sounded like you were just mashing buttons. I'm taking cover.",
    "Warning: anomalous communication detected. Preparing to purge the network.",
    "Dispatch, is this a loyalty test? Because I'll shoot whoever you want."
];

window.voreChats = [
    "Dispatch... what is happening? The walls are breathing.",
    "I don't feel safe out here anymore. Something is hunting us.",
    "Did anyone just see the sky blink?",
    "My cruiser's dashboard is melting... or am I going crazy?",
    "I need backup! Not for criminals... for the shadows. They're moving.",
    "Dispatch, my reflection in the mirror just smiled at me. I'm leaving.",
    "Is anyone else hearing that low hum? It's inside my skull.",
    "I swear the pavement just swallowed a stray dog.",
    "I want to go home, Dispatch. Please let us go home.",
    "They told us we'd be protecting the city. They didn't tell us from what.",
    "I'm locking myself in the trunk. Do not send anyone.",
    "The streetlights are all pointing at me.",
    "My sidearm just whispered my name.",
    "There are teeth in the concrete. Huge teeth.",
    "I'm staring into the alleyway and it's staring back.",
    "Dispatch, please wake me up. I know this is a dream. Wake me up!",
    "The rain smells like copper today.",
    "I just saw my own corpse walking down 4th street.",
    "Something is under the city. It's waking up.",
    "My partner vanished when I blinked.",
    "I'm not shooting anyone. I don't want to make it angry.",
    "Every civilian face is completely blank. No eyes. No mouths.",
    "The radio static sounds like screaming... is that you, Dispatch?",
    "I can't remember my own name anymore. Where am I?",
    "Did the sun just turn black?",
    "We are not in control. We never were.",
    "I found a door in the middle of the street. It's open.",
    "Gravity feels... optional right now.",
    "They're coming from the sewers. Millions of them. But they look like us.",
    "I just arrested a shadow. My cuffs went right through it.",
    "Who is Gordon Freeman? Why does my brain hurt when I say it?",
    "My blood is turning cold. I think I died yesterday.",
    "I beg you, send an extraction team! But don't let them look at the sky!",
    "The neon signs are spelling out my sins.",
    "I'm hiding under the cruiser. Tell my family to forget me.",
    "My weapon is useless against this.",
    "I fired a full mag into it... it just absorbed the bullets.",
    "We breached the apartment, but the geometry inside is all wrong. Endless hallways.",
    "There's a knock on the patrol car window. But I'm parked on a bridge. Over the water.",
    "The sirens sound like laughing.",
    "I'm taking off my badge. This is not our city anymore.",
    "The birds. Look at the birds. They're completely frozen in mid-air.",
    "I tried to run, but everywhere I go, I end up back here.",
    "It's too quiet. Even the wind stopped.",
    "My heart isn't beating, Dispatch. I checked three times.",
    "We're just food. That's all we are.",
    "The buildings are leaning over, trying to crush us.",
    "I can hear the city thinking.",
    "Don't trust unit 47. He has entirely too many joints in his arms now.",
    "I'm dropping my weapon and walking into the fog. Good luck."
];

window.greetingChats = [
    "Unit checking in. Ready for duty.",
    "Dispatch, I'm 10-8 and on patrol.",
    "Clocked in. Let's see what the city throws at us today.",
    "I'm online. Keep me posted on any 10-31s.",
    "Cruiser fueled and armed. Standing by.",
    "Starting my shift. Hope it's a quiet one. (Yeah right).",
    "Unit online. Send me the active warrants.",
    "I'm back on the streets. Let's hunt.",
    "Dispatch, I'm available for assignment.",
    "Just finished my coffee. Ready to enforce.",
    "I'm 10-8. Let's make this city safe.",
    "Signing on. May the odds be in our favor.",
    "I'm here. What's the situation out there?",
    "Unit is active. Ready to respond.",
    "Let's get to work, Dispatch.",
    "I'm on duty. Awaiting dispatch.",
    "Ready to roll. Send me a location.",
    "I'm 10-8. Let's crack some skulls.",
    "Reporting for duty. Let's do this.",
    "I'm online. Keep the comms clear.",
    "Unit is available. Hit me.",
    "Starting patrol route. Sector 4 is clear.",
    "I'm here. Let's clean up these streets.",
    "Clocked in. Ready for the chaos.",
    "I'm 10-8. Awaiting orders.",
    "Ready to enforce the law, Dispatch.",
    "I'm online. What's the damage today?",
    "Unit is active. Standing by for tasking.",
    "Let's make some arrests, Dispatch.",
    "I'm on duty. Keep an eye on me.",
    "Ready to respond. Send me the coordinates.",
    "I'm 10-8. Let's get moving.",
    "Reporting for duty. Let's keep it safe.",
    "I'm online. Awaiting dispatch.",
    "Unit is available. Let's go.",
    "Starting patrol. Sector 7 is quiet.",
    "I'm here. Let's take them down.",
    "Clocked in. Ready for anything.",
    "I'm 10-8. Awaiting assignment.",
    "Ready to roll. Let's do this, Dispatch.",

    "Hey! Anyone want to grab coffee near Sector 4?",
    "Yo, how's the patrol going?",
    "Just clocked in. What did I miss?",
    "Sup guys, another beautiful day in the dystopia.",
    "Hello from the east district. Quiet tonight.",
    "Greetings, fellow enforcers.",
    "Hey! Stop hogging the radio.",
    "Anyone got eyes on that stolen hover-car?",
    "Morning! If you can call it morning through the smog.",
    "Howdy! Watch out for the potholes on 9th ave.",
    "Hey man, I heard you got promoted!",
    "Yo! Just got a fresh supply of stun batons.",
    "Hello everyone! Keep your heads down today.",
    "Hey! Need backup over here just to eat my donut in peace.",
    "Sup! Did you finish that paperwork from yesterday?",
    "Greetings from the holding cells. It's loud in here.",
    "Hey, buddy! Long time no see on the dispatch channel.",
    "Yo! Who's buying lunch today?",
    "Hi guys! Stay alert out there.",
    "Hey! My cruiser's AC is broken again.",
    "Sup! Just chasing down some petty thieves.",
    "Hello! Anybody else bored out of their mind?",
    "Hey man, watch your six in the industrial zone.",
    "Yo! Let's wrap this shift up quick.",
    "Hi! Checking in from the rooftop patrol.",
    "Hey! Have you seen the new rookie? Absolute mess.",
    "Sup! I need a coffee IV drip right now.",
    "Hello from the traffic division! Send help, it's terrible.",
    "Hey! Don't let the captain catch you sleeping.",
    "Yo! What's the bounty on Freeman up to now?",
    "Hi guys, keep the chatter down, I have a headache.",
    "Hey! Anyone want to swap shifts on Friday?",
    "Sup! Just cleared a squatter camp.",
    "Hello! This radio is full of static.",
    "Hey man, keep your vest tight.",
    "Yo! First one back to the precinct wins a prize.",
    "Hi! My taser is acting up today.",
    "Hey! Let's go bust some skulls.",
    "Sup! Anyone else feel like we're just pawns in a simulation?",
    "Hello! Ready for some action.",
    "Hey! Got my eyes peeled.",
    "Yo! Check out the cyberware on that guy.",
    "Hi! Reporting for duty.",
    "Hey! Let's make this city safe.",
    "Sup! Another day, another dollar... wait, we use credits.",
    "Hello! Stay safe out there.",
    "Hey! Keep your comms linked.",
    "Yo! See you at the briefing.",
    "Hi! Over and out for a coffee break.",
    "Hey! Good luck on patrol."
];

window.yellLines = [
                "Clear the channel! Both of you! Act like professionals!",
                "Cut the chatter! This is an official frequency!",
                "If you two don't shut up, I'm writing you both up. Clear the air!",
                "Enough! Keep the channel clear for actual emergencies!"
            ];

window.banterLines = [

    "I swear to god if one more officer calls me a 'good boy' I'm transferring precincts.",
    "Has anyone else noticed the new recruits are... a bit eccentric? What's with the purple socks?",
    "I'm trying to write a serious police report and the guy next to me is fixing his skirt. I can't.",
    "If I get complimented on my posture one more time during a shootout, I'm quitting.",
    "Listen, I support everyone, but why does my partner insist on calling the suspects 'bestie'?",
    "Can someone please explain to me why half the force is talking about their outfits right now?",
    "I just got hit on by an officer while I was bleeding out. HR is getting a call.",
    "Is 'fabulous' a valid tactical strategy? Because someone here seems to think so.",
    "My partner just complained that the blood stains are clashing with his uniform colors. Unbelievable.",
    "I miss the old days when cops just drank black coffee and glared at people.",

                "Man, the synth-rations at the precinct taste like cardboard today.",
                "Anyone want to trade shifts on Friday? I need to get out of this sector.",
                "I swear my cruiser's AC is blowing hot air again.",
                "Did you see that new cyberware ad? Total ripoff.",
                "I'm so tired I could sleep standing up.",
                "If dispatch gives me one more noise complaint, I'm quitting."
            ,
"I'm currently 10-6 at the donut shop. Code 3 emergency, they only have one glazed left.",
"Dispatch, my cruiser's engine sounds weird. I'm taking the rest of the shift off to investigate.",
"Can someone else take that 10-31? I just found a really comfortable parking spot.",
"I'm officially on strike until the Chief buys better coffee for the break room.",
"If I don't acknowledge the radio, the crime doesn't legally exist, right?",
"I'm currently investigating the inside of my eyelids for suspicious activity.",
"Dispatch, my radio is breaking up. I'm just going to mute it for the next 4 hours.",
"Did you just say armed robbery? Because my radio heard 'go take a nap'.",
"I am currently hiding from my responsibilities. Do not disturb.",
"If I ignore the 911 calls, they usually just resolve themselves.",
"I'm 10-7 for a mental health break. The suspect was being mean to me.",
"Can the SWAT team handle this noise complaint? It's all the way across town.",
"I'm not writing a report for this. Let's just say a ghost did it.",
"I'm on a top-secret undercover mission in the break room.",
"I've mastered the art of looking busy while doing absolutely nothing.",
"My cruiser is out of gas. No, I will not walk to the gas station.",
"Dispatch, tell the caller to solve their own crimes. I'm busy watching a movie.",
"I dropped my donut in the dirt. Requesting grief counseling and a week of paid leave.",
"I'm 10-8, but honestly, pretend I'm 10-7.",
"Can we automate the arrests? Getting out of the car is exhausting.",
"I'm too sober for this shift. Going on break.",
"My uniform shrank in the wash, I literally cannot move my arms to arrest anyone.",
"I'll investigate the homicide after my lunch break. Bodies don't go anywhere.",
"I let the suspect go because I didn't want to do the paperwork. Oops."
];

window.wantedLines = [
                            `Dispatch, I just had a run-in with {name}. I'm flagging them as Wanted. Total scum.`,
                            `{name} just pulled a weapon and ran. Declaring them Wanted!`,
                            `Putting out a warrant for {name}. They're on the Wanted list now.`,
                            `Be advised, {name} is now considered Armed and Wanted in my sector.`
                        ];

window.suspLines = [
                            `This guy {name} bumped into me. Declaring him Suspicious.`,
                            `Dispatch, {name} is acting extremely erratic. Marking them Suspicious in the directory.`,
                            `Got my eye on {name}. Putting a Suspicious flag on their dossier.`,
                            `{name} refused to answer questions. They're Suspicious now.`
                        ];


